passportxyz/passport

- app/package.json
- app/pages/_app.tsx
- database-client/package.json
- package.json
- yarn.lock
Didnt test entire flow, but did run app and authenticate using did-session pkh/siwe
> feat(app): add ceramic did-session pkh flag support and dependencies

- README.md
for dopes like me who just copy whats in the setup instructions
> updates readme to have cd in it

- app/__tests__/components/ProviderCards/PoapCard.test.tsx
- app/components/ProviderCards/PoapCard.tsx
- app/components/VerifyModal.tsx
> feat(poap): Styling & content of modals

- app/components/ProviderCards/BrightidCard.tsx
- app/components/ProviderCards/EnsCard.tsx
- app/components/ProviderCards/FacebookCard.tsx
- app/components/ProviderCards/GoogleCard.tsx
- app/components/ProviderCards/PoapCard.tsx
- app/components/ProviderCards/PohCard.tsx
- app/components/ProviderCards/TwitterCard.tsx
Adding manual invocation of RUM SDK to add errors from provider cards.
[#139]
> feat(app): manually add errors to Datadog RUM from provider Cards

- app/__mocks__/@self.id/framework/index.js
- app/__tests__/pages/Dashboard.test.tsx
- app/pages/Dashboard.tsx
> feat(app): adds spinner to prompt user to sign wallet before loading passport

- app/components/ProviderCards/BrightidCard.tsx
- app/components/ProviderCards/EnsCard.tsx
- app/components/ProviderCards/FacebookCard.tsx
- app/components/ProviderCards/GoogleCard.tsx
- app/components/ProviderCards/PoapCard.tsx
- app/pages/index.tsx
Trying a few different logging methods to see which gives the cleanest results in Datadog.
> feat(app): datadog front-end logging cleanup

- app/context/userContext.tsx
- database-client/src/ceramicClient.ts
This PR enables logging to Datadog in the ceramicClient. 
This fixes issue #215
> feat(logging): have added a logger object to ceramicClient

- app/pages/Home.tsx
> feat(app): adds Powered By Ceramic Network link

- database-client/src/ceramicClient.ts
This addresses the issue: #227
> fix(database-client): handle loading passport with no stamps

- app/context/userContext.tsx
This PR ensures the user can only connect their wallet on `mainnet` (which will ensure Ceramic data is also only pulled from mainnet).
--
Tested locally
> fix(app): ensures Ceramic can only be connected to mainnet

- app/package.json
- database-client/package.json
- package.json
- schemas/package.json
- yarn.lock
@ceramicnetwork/cli: ^2.0.2 -> ^2.3.0
@ceramicnetwork/common: ^2.0.0 -> ^2.2.0
@ceramicnetwork/http-client: ^2.0.0 -> ^2.2.0
@ceramicnetwork/stream-tile: ^2.0.0 -> ^2.2.1
@glazed/devtools: ^0.1.6 -> ^0.2.0
resolutions: dids: ^3.1.0 -> ^3.2.0
[resolves #237]
> build: upgrade ceramic libraries

- app/pages/Dashboard.tsx
- app/tailwind.config.js
> feat(app): updates wallet signature alert style

- app/__tests__/components/CardList.test.tsx
- app/components/CardList.tsx
- app/components/LoadingCard.tsx
- app/pages/Dashboard.tsx
- restyle Passport loading spinner to more than just a Spinner
- add loading car coponent and list for passport loading state
[finishes #270]
> feat(app): restyle loading states on dashboard page

- app/package.json
- database-client/package.json
- iam/package.json
- identity/package.json
- schemas/package.json
- types/package.json
affects `app`, `database-client`, `iam`, `identity`, `schemas`, `types`
* bump to version 1.0.0
[resolves #109]
> Bump release v1.0.0

- app/__test-fixtures__/contextTestHelpers.tsx
- app/__tests__/components/Card.test.tsx
- app/__tests__/components/ProviderCards/BrightidCard.test.tsx
- app/__tests__/components/ProviderCards/DiscordCard.test.tsx
- app/__tests__/components/ProviderCards/EnsCard.test.tsx
- app/__tests__/components/ProviderCards/FacebookCard.test.tsx
- app/__tests__/components/ProviderCards/GithubCard.test.tsx
- app/__tests__/components/ProviderCards/GoogleCard.test.tsx
- app/__tests__/components/ProviderCards/LinkedinCard.test.tsx
- app/__tests__/components/ProviderCards/PoapCard.test.tsx
- app/__tests__/components/ProviderCards/PohCard.test.tsx
- app/__tests__/components/ProviderCards/TwitterCard.test.tsx
- app/components/Card.tsx
- app/components/ProviderCards/BrightidCard.tsx
- app/components/ProviderCards/DiscordCard.tsx
- app/components/ProviderCards/EnsCard.tsx
- app/components/ProviderCards/FacebookCard.tsx
- app/components/ProviderCards/GithubCard.tsx
- app/components/ProviderCards/GoogleCard.tsx
- app/components/ProviderCards/LinkedinCard.tsx
- app/components/ProviderCards/PoapCard.tsx
- app/components/ProviderCards/PohCard.tsx
- app/components/ProviderCards/TwitterCard.tsx
- app/context/ceramicContext.tsx
- database-client/integration-tests/ceramicDatabaseTest.ts
- database-client/src/ceramicClient.ts
- types/src/index.d.ts
This fixes issues #208 and #330
integration tests are still WIP.
> Feature/delete stamp + fix: handle failure to load stamp in passport

- iam/__tests__/twitterTweets.test.ts
- iam/src/index.ts
- iam/src/procedures/twitterOauth.ts
- iam/src/providers/twitterTweets.ts
> feat(iam): adds twitter greater than 10 tweets/posts stamp provider

- iam/__tests__/twitterFollower.test.ts
- iam/src/index.ts
- iam/src/procedures/twitterOauth.ts
- iam/src/providers/TwitterFollower.ts
Following Stamps are included:
>100, >500, >=1000, >5000
Closes #363
Closes #365
Closes #366
Closes #370
> feat(iam): adds twitter follower stamp provider

- database-client/README.md
- database-client/integration-tests/ceramicDatabaseTest.ts
feat(database-client): integration test for handling the failure to load individual stamps
* this addresses this issues: #346 and #330
> integration test for handling the failure to load individual stamps

- iam/__tests__/clearTextGithubOrg.test.ts
- iam/src/index.ts
- iam/src/providers/clearTextGithubOrg.ts
- iam/src/providers/github.ts
This builds off of https://github.com/gitcoinco/passport/pull/393 to return a cleartext VC validating that a user belongs to given github organzation
> GitHub org clear text provider

- iam/__tests__/facebookFriends.test.ts
- iam/__tests__/facebookProfilePicture.test.ts
- iam/src/index.ts
- iam/src/providers/facebookFriends.ts
- iam/src/providers/facebookProfilePicture.ts
> Facebook friends

- iam/.env-example.env
- iam/__tests__/gitcoinGrantsContributorStatistics.test.ts
- iam/__tests__/gitcoinGrantsGranteeStatistics.test.ts
- iam/__tests__/gitcoinGrantsStatistics.test.ts
- iam/__tests__/github.test.ts
- iam/src/index.ts
- iam/src/providers/gitcoinGrantsContributorStatistics.ts
- iam/src/providers/gitcoinGrantsGranteeStatistics.ts
- iam/src/providers/gitcoinGrantsStatistics.ts
Recovering the gitcoin iam providers
> Recovering gitcoin iam providers

- infra/production/index.ts
- infra/review/index.ts
- infra/staging/index.ts
> chore(iam): add secrets to pulumi

- infra/ceramic-testnet/index.ts
Pushing out the changes to prod, as prod seems to have troubles at the moment.
> update version, tag, and fix reboot issue

- iam/.env-example.env
- iam/__tests__/ethTransactions.test.ts
- iam/src/index.ts
- iam/src/providers/ethTransactions.ts
- infra/production/index.ts
- infra/review/index.ts
- infra/staging/index.ts
Will ask Leon about the edge cases (count only successful transactions, and transactions FROM the user) during stand-up
> feat(iam): adds providers for ETH mainnet transactions, env variables, and infra secrets

- iam/.env-example.env
- iam/__tests__/nft.test.ts
- iam/src/providers/nft.ts
- infra/production/index.ts
- infra/review/index.ts
- infra/staging/index.ts
This fixes: https://github.com/gitcoinco/passport/issues/469
> feat(iam): adding stamp for holding at least 1 NFT

- iam/src/index.ts
> feat(iam): registering nft provider in list of providers

- .github/workflows/ceramic-promote-production.yml
- .github/workflows/ceramic-promote-staging.yml
This action should provision the ceramic node to production.
This closes: #481
> feat(infra): gh action for deploying ceramic to production

- iam/__tests__/lens.test.ts
- iam/src/index.ts
- iam/src/providers/lens.ts
- infra/production/index.ts
- infra/review/index.ts
- infra/staging/index.ts
> feat(iam): adds lens default profile stamp

- app/context/userContext.tsx
- app/package.json
- yarn.lock
This solves: https://github.com/gitcoinco/passport/issues/304
> Feat(app): persisting user sessions between reloads of the app

- iam/__tests__/zkSync.test.ts
- iam/src/index.ts
- iam/src/providers/zkSync.ts
> feat(iam): adding zkSync provider

- iam/__tests__/communityStaking.test.ts
- iam/__tests__/selfStaking.test.ts
- iam/src/providers/communityStaking.ts
- iam/src/providers/selfStaking.ts
- Sets thresholds to 1, 10, 100
Closes #487
> feat(iam): updates self/community staking thresholds for each tier

- app/__test-fixtures__/contextTestHelpers.tsx
- app/components/CardList.tsx
- app/components/PlatformCards/FacebookPlatform.tsx
- app/components/PlatformCards/index.tsx
- app/config/providers.ts
- app/context/ceramicContext.tsx
- types/src/index.d.ts
This PR exposes all Facebook Providers via the Facebook Platform sidebar.
--
Closes: #450 #452 #453
> feat(app): implements sidebar for Facebook Platform

- app/components/CardList.tsx
- app/components/PlatformCards/DiscordPlatform.tsx
- app/components/PlatformCards/index.tsx
This PR exposes Discord Provider via the Discord Platform sidebar.
--
Closes [#457](https://github.com/gitcoinco/passport/issues/457) [#458](https://github.com/gitcoinco/passport/issues/458) [#459](https://github.com/gitcoinco/passport/issues/459)
> feat(app): adds Discord sidebar, toggle, and verify for Discord data point

- app/components/CardList.tsx
- app/components/PlatformCards/BrightidPlatform.tsx
- app/components/PlatformCards/index.tsx
- app/config/platforms.ts
Implements Bright ID sidebar and stamp verification & management
Closes #504
> feat(app): adds brightid platform sidebar content

- app/components/CardList.tsx
Closes: #[530](https://github.com/gitcoinco/passport/issues/530)
> feat(app): adds verified states to platform cards

- iam/__tests__/fiveOrMoreGithubRepos.test.ts
- iam/__tests__/github.test.ts
- iam/__tests__/githubFollowers.test.ts
- iam/__tests__/githubForkedRepoProvider.test.ts
- iam/__tests__/githubStarredRepoProvider.test.ts
- iam/src/providers/fiveOrMoreGithubRepos.ts
- iam/src/providers/gitcoinGrantsStatistics.ts
- iam/src/providers/github.ts
- iam/src/providers/githubFollowers.ts
- iam/src/providers/githubForkedRepoProvider.ts
- iam/src/providers/githubStarredRepoProvider.ts
Fixes the GitHub token caching issue between requests
> fix(iam): GitHub caching access token

- app/components/CardList.tsx
- app/config/providers.ts
- app/context/userContext.tsx
- app/tailwind.config.js
Show update pill if they haven't opened popout
I also added a key to the loading component to avoid the :key error
> feat(app):  adding updated pill

- app/components/CardList.tsx
https://user-images.githubusercontent.com/6887938/188927345-1c78e96a-448b-4014-b6b4-022f6164d669.mov
> fix(app): only show updated at if they have previously verified

- app/components/PlatformCards/GtcStakingPlatform.tsx
- app/components/SideBarContent.tsx
- app/config/providers.ts
- app/tailwind.config.js
- adds infoElement parameter to sidebarContent
- shows id staking info and link when verifying stake amount
Closes #553
> feat(app): adds link to id staking in sidebar

- app/config/providers.ts
> fix(app): updates gtc staking provider titles to include "More than"  prefix

- iam/__tests__/gnosisSafe.test.ts
- iam/src/index.ts
- iam/src/providers/gnosisSafe.ts
> feat(iam): adding gnosis safe stamp

- database-client/src/ceramicClient.ts
> fix(app): handle empty passport (empty object, stamps is undefined)

- .github/workflows/ci.yml
> feat(ci): test ci workflow with local ceramic node

- app/components/PlatformCards/BrightidPlatform.tsx
> feat(app): removes brightid verification modal and shows connection modal

- app/config/providers.ts
- iam/__tests__/lens.test.ts
- iam/src/providers/lens.ts
> fix(app, iam): modifies lens stamp to verify lens handle

- app/context/userContext.tsx
This fixes build failures in passport/app
> fix(app): fix importing OnboardAPI form the right lib

- app/__tests__/pages/index.test.tsx
> fix(app): mocks BroadcastChannel for index test

- app/pages/Dashboard.tsx
> fix(app): horizontally align header

- .github/workflows/ci.yml
- app/components/CardListV2.tsx
- app/components/GenericOauthPlatform.tsx
- platforms/__tests__/Twitter/twitterFollower.test.ts
- platforms/__tests__/Twitter/twitterTweets.test.ts
- platforms/index.ts
- platforms/src/Twitter/Providers/TwitterAuthProvider.ts
- platforms/src/Twitter/Providers/TwitterFollowerProvider.ts
- platforms/src/Twitter/Providers/TwitterTweetsProvider.ts
- platforms/src/Twitter/procedures/twitterOauth.ts
- platforms/src/index.ts
- platforms/tsconfig.json
This attempts to fix the build issues in main branch for app.
> fix(build): trying to fix app build

- app/components/CardListV2.tsx
- app/components/GenericOauthPlatform.tsx
- iam/src/index.ts
- platforms/src/Facebook/App-Bindings.ts
- platforms/src/Facebook/Providers-config.ts
- platforms/src/Facebook/Providers/facebook.ts
- platforms/src/Facebook/Providers/facebookFriends.ts
- platforms/src/Facebook/Providers/facebookProfilePicture.ts
- platforms/src/Facebook/__tests__/facebook.test.ts
- platforms/src/Facebook/__tests__/facebookFriends.test.ts
- platforms/src/Facebook/__tests__/facebookProfilePicture.test.ts
- platforms/src/Facebook/index.ts
- platforms/src/index.ts
- platforms/src/types.ts
> 623  facebook abstraction

- app/components/GenericEVMPlatform.tsx
- app/components/GenericOauthPlatform.tsx
- platforms/package.json
- platforms/src/Twitter/App-Bindings.ts
- yarn.lock
This fixes the twitter stamp (implements the getOAuthUrl for Twitter provider)
> 622 GitHub abstraction

- app/components/CardListV2.tsx
- iam/src/index.ts
- platforms/src/ETH/App-Bindings.ts
- platforms/src/ETH/Providers-config.ts
- platforms/src/ETH/Providers/ethErc20Possession.ts
- platforms/src/ETH/Providers/ethTransactions.ts
- platforms/src/ETH/Providers/index.ts
- platforms/src/ETH/__tests__/ethErc20PossessionEth.test.ts
- platforms/src/ETH/__tests__/ethTransactions.test.ts
- platforms/src/ETH/index.ts
- platforms/src/index.ts
> feat(app, iam, platforms): adds ETH platform abstraction

- app/components/CardListV2.tsx
- app/components/DoneToastContent.tsx
- app/components/GenericEVMPlatform.tsx
- app/components/GenericOauthPlatform.tsx
- app/components/SideBarContent.tsx
- iam/src/index.ts
- platforms/package.json
- platforms/src/POAP/App-Bindings.ts
- platforms/src/POAP/Providers-config.ts
- platforms/src/POAP/Providers/poap.ts
- platforms/src/POAP/__tests__/poap.test.ts
- platforms/src/POAP/index.ts
- platforms/src/Twitter/__tests__/twitter.test.ts
- platforms/src/Twitter/__tests__/twitterFollower.test.ts
- platforms/src/Twitter/__tests__/twitterTweets.test.ts
- platforms/src/index.ts
- platforms/src/platforms-config.ts
- platforms/src/procedure-router.ts
- platforms/src/types.ts
Closes #631 
- Moves twitter tests to /platforms/src/Twitter
- Updates Twitter Provider imports in IAM index.ts
- Moves PLATFORM_ID and PROVIDER_ID to platforms/types. Then updates the types used in app
> feat(app, iam, platforms): adds poap abstraction

- app/__tests__/components/SideBarContent.test.tsx
- app/components/GenericEVMPlatform.tsx
- app/components/SideBarContent.tsx
> 682 sidebar test

- app/components/CardListV2.tsx
- app/components/GenericPlatform.tsx
- iam/src/index.ts
- platforms/src/Linkedin/App-Bindings.ts
- platforms/src/Linkedin/Providers-config.ts
- platforms/src/Linkedin/Providers/linkedin.ts
- platforms/src/Linkedin/__tests__/linkedin.test.ts
- platforms/src/Linkedin/index.ts
- platforms/src/index.ts
> feat(platforms, app, iam): adds linkedin abstraction

- database-client/__tests__/CeramicDatabase.test.ts
- database-client/src/ceramicClient.ts
> fix(#680): make stamp loading more resilient, handle faulty stamps

- app/components/CardListV2.tsx
- iam/src/index.ts
- platforms/src/GtcStaking/App-Bindings.ts
- platforms/src/GtcStaking/Providers-config.ts
- platforms/src/GtcStaking/Providers/communityStaking.ts
- platforms/src/GtcStaking/Providers/index.ts
- platforms/src/GtcStaking/Providers/selfStaking.ts
- platforms/src/GtcStaking/__tests__/communityStaking.test.ts
- platforms/src/GtcStaking/__tests__/selfStaking.test.ts
- platforms/src/GtcStaking/index.ts
- platforms/src/index.ts
> feat(identity staking): abstraction for identity staking

- database-client/src/ceramicClient.ts
> fix(#680): loading ceramix streams using HTTP API

- platforms/src/Discord/App-Bindings.ts
- platforms/src/ETH/App-Bindings.ts
- platforms/src/Ens/App-Bindings.ts
- platforms/src/Facebook/App-Bindings.ts
- platforms/src/GTC/App-Bindings.ts
- platforms/src/GitPOAP/App-Bindings.ts
- platforms/src/Gitcoin/App-Bindings.ts
- platforms/src/Github/App-Bindings.ts
- platforms/src/GnosisSafe/App-Bindings.ts
- platforms/src/Lens/App-Bindings.ts
- platforms/src/Linkedin/App-Bindings.ts
- platforms/src/NFT/App-Bindings.ts
- platforms/src/POAP/App-Bindings.ts
- platforms/src/Poh/App-Bindings.ts
- platforms/src/Snapshot/App-Bindings.ts
- platforms/src/Twitter/App-Bindings.ts
- platforms/src/ZkSync/App-Bindings.ts
- platforms/src/types.ts
- platforms/src/utils/platform.ts
> 709 base platform

- app/components/PlatformCard.tsx
- platforms/src/Facebook/Providers-config.ts
- platforms/src/Github/Providers-config.ts
- platforms/src/Twitter/Providers-config.ts
- platforms/src/index.ts
- platforms/src/types.ts
> feat(app, platforms): enables platform card update pill for Facebook, Twitter and Github stamps

- platforms/src/Google/Providers/__tests__/google.test.ts
- platforms/src/Google/Providers/google.ts
> feat(google): better error messages + console logs for google provider

- iam/src/index.ts
> fix(iam): adds platforms provider implementation of Brightid

- iam/.env-example.env
- platforms/src/procedure-router.ts
Very open to other solutions, this was the best I could think of at the moment for modifying the path to the static html file to work locally as well as within the container
> fix(platforms): resolve path for new docker build

- platforms/src/Gitcoin/Providers/__tests__/gitcoinGrantsStatistics.test.ts
- platforms/src/Gitcoin/Providers/gitcoinGrantsStatistics.ts
- platforms/src/Github/Providers/__tests__/github.test.ts
- platforms/src/Github/Providers/github.ts
- platforms/src/Google/Providers/__tests__/google.test.ts
- platforms/src/Google/Providers/google.ts
- platforms/src/procedure-router.ts
This aims to make it possible to debug what is happening when verification fails for some of the providers.
> Enhance logs with controller address

- iam/.env-example.env
- infra/production/index.ts
- infra/review/index.ts
- infra/staging/index.ts
- platforms/src/GtcStaking/Providers/communityStaking.ts
- platforms/src/GtcStaking/Providers/selfStaking.ts
> feat(platforms): updating graph endpoint

- .gitignore
- app/components/GenericBanner.tsx
- app/components/GenericPlatform.tsx
- platforms/src/Ens/App-Bindings.ts
- platforms/src/Gitcoin/App-Bindings.ts
- platforms/src/GnosisSafe/App-Bindings.ts
- platforms/src/GtcStaking/App-Bindings.ts
- platforms/src/NFT/App-Bindings.ts
- platforms/src/types.ts
- platforms/src/utils/platform.ts
closes #816
Co-authored-by: Lucian <lucian@gitcoin.co>
> feat: add heading and cta to stamp sidebar banner

- infra/ceramic-testnet/index.ts
fixes: [#868](https://github.com/gitcoinco/passport/issues/868)
> feat(infra-testnet): update ceramic node

- infra/ceramic-mainnet/index.ts
> feat(infra): bump ceramic mainnet to 2.20.0

- platforms/src/GtcStaking/App-Bindings.ts
> chore: update gtc staking banner text

- app/__test-fixtures__/contextTestHelpers.tsx
- app/__tests__/components/ExpiredStampModal.test.tsx
- app/__tests__/context/ceramicContext.test.tsx
- app/components/ExpiredStampModal.tsx
- app/context/ceramicContext.tsx
- app/pages/Dashboard.tsx
- app/utils/helpers.tsx
> 810 removing expired stamps

- .github/workflows/ci.yml
- app/__tests__/context/userContext.test.tsx
- app/context/userContext.tsx
- database-client/integration-tests/ceramicDatabaseTest.ts
> feat: disconnect wallet on expired session

- infra/ceramic-testnet/index.ts
This relates to: https://github.com/gitcoinco/passport/issues/898
This PR create an EFS instance and mounts it on `/data/ipfs/` in the IPFS task.
Fixes: #898
> feat(infra): adding efs mount to /data/ipfs in ipfs task for testnet

- app/context/userContext.tsx
> feat(app): request unique nonce from server for authentication

- .github/workflows/iam-cd-review.yml
- infra/review/index.ts
This fixes the domain for review
> fix(infra,domain): this changes the domain for review

- platforms/src/ETH/Providers/ethTransactions.ts
- platforms/src/ETH/__tests__/ethTransactions.test.ts
> fix(provider,eth): fix provider that checks if the amount of ETH spent on gas is > 0.5 ETH

- .github/workflows/iam-promote-staging.yml
- infra/staging/index.ts
This fixes the domain for staging
> Fix infra staging domain

- app/components/Footer.tsx
- app/package.json
- app/tailwind.config.js
> feat: display git commit url in footer

- app/__test-fixtures__/contextTestHelpers.tsx
- app/__tests__/components/ExpiredStampModal.test.tsx
- app/__tests__/context/userContext.test.tsx
- app/components/ExpiredStampModal.tsx
- app/context/userContext.tsx
- app/jest.config.ts
- app/package.json
- yarn.lock
> test(interface): added tests for userContext, including multichain

- app/__test-fixtures__/toastTestHelpers.tsx
- app/__tests__/components/GenericPlatform.test.tsx
- app/__tests__/components/RemoveStampModal.test.tsx
fixes https://github.com/gitcoinco/passport/issues/751
> test(interface): added tests for done toasts

- app/package.json
> fix: add git hash in prod-start

- app/components/Footer.tsx
- app/pages/Home.tsx
> 1122 footer updates

- platforms/src/ETH/Providers/ethTransactions.ts
- platforms/src/ETH/__tests__/ethTransactions.test.ts
> 1093 eth tx bug

- platforms/src/ZkSync/Providers-config.ts
> fix(app): updated zkSync info to reflect zkSync1.0

- app/components/InitialWelcome.tsx
> fix(app): text update

- app/components/RefreshMyStampsModal.tsx
- app/components/RefreshMyStampsModalContentCard.tsx
- platforms/src/ZkSync/App-Bindings.ts
> 1133 missing stamp

- .github/workflows/ci.yml
https://discord.com/channels/562828676480237578/1073190200404103218/1098638359959711824
> chore(ci): move integration test before lint

- app/components/RefreshMyStampsModalContentCard.tsx
- app/components/RefreshMyStampsSelector.tsx
Fixes: https://github.com/gitcoinco/passport/issues/1116
> Functionality to enable all stamp data points when platform toggle is set to "on"

- app/components/RefreshMyStampsModalContent.tsx
- app/components/RefreshMyStampsSelector.tsx
- iam/src/utils/challenge.ts
> feat: confirm multiple stamps with one signature

- app/components/CardList.tsx
- app/components/GenericPlatform.tsx
- app/components/SideBarContent.tsx
Closes #1132 
Verify button logic needs to be tested on review for stamp w/ multiple providers EG twitter account name, 100 followers etc
> fixes(app): updates verifyButton Logic & drawercloseButton bg

- app/components/CardList.tsx
- app/components/GenericPlatform.tsx
- app/components/SideBarContent.tsx
closes #1132 and it's pretty!
verifyButton logic needs to be tested on stamp that has multiple providers eg twitter profile + followers etc
> fix(app): update verifyButton logic and drawerclosebutton

- app/__tests__/components/RefreshMyStampsModalContentCardList.test.tsx
- app/components/RefreshMyStampsModalContent.tsx
> feat: add data storage info to stamps modal

- app/components/RefreshMyStampsModalContent.tsx
> chore(app): updates 1 click language

- app/components/RefreshMyStampsModalContent.tsx
> 1181 language update

- app/__tests__/components/RefreshMyStampsModalContent.test.tsx
- app/components/RefreshMyStampsModalContent.tsx
- app/utils/helpers.tsx
- iam/__tests__/challenge.test.ts
> 1150 test issue multiple stamps

- platforms/src/NFT/Providers/__tests__/nft.test.ts
- platforms/src/NFT/Providers/nft.ts
> fix(platforms): use correct alchemy url

- app/__tests__/components/RefreshMyStampsModalContentCard.test.tsx
- app/__tests__/components/RefreshMyStampsModalContentCardList.test.tsx
- app/__tests__/components/RefreshMyStampsSelector.test.tsx
- app/components/RefreshMyStampsModalContent.tsx
- app/components/RefreshMyStampsModalContentCard.tsx
- app/components/RefreshMyStampsModalContentCardList.tsx
- app/components/RefreshMyStampsSelector.tsx
> 1161 test stamp selection

- app/__tests__/pages/Home.test.tsx
- app/__tests__/utils/utils.test.ts
- app/components/RefreshMyStampsModalContent.tsx
- app/pages/Home.tsx
- app/utils/helpers.tsx
> feat(app): hide onboarding flow checkbox

- app/components/RefreshMyStampsModalContentCard.tsx
- app/components/RefreshMyStampsSelector.tsx
> feat(app): collapse credentials of unselected stamp in 1-click modal

- app/components/ExpiredStampModal.tsx
- app/context/ceramicContext.tsx
> fix(app): add link to kb article & add error log to ceramicContext

- app/config/providers.ts
- platforms/src/GuildXYZ/App-Bindings.ts
- platforms/src/GuildXYZ/Providers-config.ts
- platforms/src/GuildXYZ/Providers/guildXYZ.ts
- platforms/src/GuildXYZ/__tests__/guildXYZ.test.ts
> refactor(platforms): update wording and admin requirements

- app/components/JsonOutputModal.tsx
- app/components/PageWidthGrid.tsx
> fix(app): add border color

- infra/production/index.ts
Fixes: https://github.com/gitcoinco/passport/issues/1253
> infra(iam): bump IAM specs + enable autoscaling

- infra/production/index.ts
> 1253 stamp verification failures 1

- app/context/ceramicContext.tsx
> fix(app): ff guld stamp on oboard

- .github/workflows/release_and_deploy_passport.yml
> feat(infra): adding release and deploy workflow

- app/components/NoStampModal.tsx
fixes: https://github.com/gitcoinco/passport/issues/930
> Changes button verbiage to 'wallet' for additional signer

- app/components/AdditionalStampModal.tsx
- app/components/DoneToastContent.tsx
- app/components/Footer.tsx
- app/components/GenericBanner.tsx
- app/components/GenericPlatform.tsx
- app/components/JsonOutputModal.tsx
- app/components/NoStampModal.tsx
- app/components/PageWidthGrid.tsx
- app/components/RefreshMyStampsModal.tsx
- app/components/RefreshMyStampsModalContent.tsx
- app/components/RefreshMyStampsModalContentCard.tsx
- app/components/RemoveStampModal.tsx
- app/components/WelcomeWrapper.tsx
- app/pages/Dashboard.tsx
- app/pages/_app.tsx
- app/public/ipfs-404.html
- app/styles/globals.css
- app/tailwind.config.js
- app/utils/theme/setTheme.tsx
- app/utils/theme/themeWrapper.tsx
- app/utils/theme/themes.tsx
- app/utils/theme/types.tsx
- iam/src/static/bright-id-template.html
> 1272 design tokens - updating fonts

- app/components/SyncToChainButton.tsx
- app/pages/Dashboard.tsx
- iam/__tests__/easSchema.test.ts
- iam/__tests__/index.test.ts
- iam/src/index.ts
- iam/src/utils/easSchema.ts
- identity/__tests__/credentials.test.ts
- platforms/jest.config.cjs
- platforms/src/ETH/__tests__/ethTransactions.test.ts
- platforms/src/Gitcoin/Providers/index.ts
- platforms/src/Github/Providers/__tests__/githubFiveOrMoreGithubRepos.test.ts
- platforms/src/Github/Providers/__tests__/githubStarredRepoProvider.test.ts
- platforms/src/Github/Providers/githubStarredRepoProvider.ts
- platforms/tsconfig.json
- types/src/index.d.ts
> feat(iam): adjustments to eas attestation for gas optimisation

- app/__mocks__/@didtools/cacao.js
- app/components/CardList.tsx
- app/components/GenericPlatform.tsx
- app/components/PlatformCard.tsx
- app/components/SideBarContent.tsx
- app/components/StampSelector.tsx
- app/context/onChainContext.tsx
- app/pages/Dashboard.tsx
- app/pages/_app.tsx
> feat: display on-chain status for credentials of a stamp

- platforms/src/Hypercerts/Providers-config.ts
- platforms/src/Hypercerts/Providers/Hypercerts.ts
- platforms/src/Hypercerts/Providers/__tests__/Hypercerts.test.ts
fixes: #1236
Update stamp requirements per `Could you make it so they need to have at least 2 hypercerts owned for over 15 days?`
> 1236 update hypercert permissions

- .github/workflows/release_and_deploy_passport.yml
fixes https://github.com/gitcoinco/passport/issues/1090
> 1190 auto releases 1

- app/package.json
- app/scripts/postBuild.ts
> fix(app): for 1235 - put public files in "out/" for app export

- platforms/src/ZkSync/App-Bindings.ts
> 983 zksync banner

- platforms/src/ZkSync/Providers-config.ts
- platforms/src/ZkSync/Providers/zkSync.ts
- platforms/src/ZkSync/Providers/zkSyncEra.ts
- platforms/src/ZkSync/__tests__/zkSync.test.ts
- platforms/src/ZkSync/__tests__/zkSyncEra.test.ts
- platforms/src/ZkSync/index.ts
- types/src/index.d.ts
> feat: add zkSync Era credential

- app/components/BodyWrapper.tsx
- app/components/CardList.tsx
- app/components/Footer.tsx
- app/components/InitialWelcome.tsx
- app/components/PageWidthGrid.tsx
- app/components/PlatformCard.tsx
- app/components/RefreshMyStampsModal.tsx
- app/components/RefreshMyStampsModalContent.tsx
- app/components/RefreshMyStampsModalContentCard.tsx
- app/components/RefreshMyStampsSelector.tsx
- app/components/WelcomeWrapper.tsx
- app/package.json
- app/pages/Dashboard.tsx
- app/pages/Home.tsx
- app/pages/Welcome.tsx
- app/scripts/postBuild.ts
- app/styles/globals.css
- app/tailwind.config.js
- app/utils/theme/chakra/Modal.tsx
> feat(api): spacing adjustments to align with design tokens

- README.md
> 1112 documentation update

- platforms/src/GtcStaking/App-Bindings.ts
- platforms/src/GtcStaking/Providers-config.ts
- platforms/src/GtcStaking/Providers/communityStaking.ts
- platforms/src/GtcStaking/Providers/selfStaking.ts
- platforms/src/GtcStaking/__tests__/communityStaking.test.ts
- platforms/src/GtcStaking/__tests__/selfStaking.test.ts
> feat(platforms): update gtc staking levels

- iam/Dockerfile
This fixes the build failure for the iam service
> fix(iam): install proper lerna version in Dockerfile

- app/__test-fixtures__/contextTestHelpers.tsx
- app/__tests__/components/GenericPlatform.test.tsx
- app/__tests__/context/ceramicContext.test.tsx
- app/components/GenericPlatform.tsx
- app/context/ceramicContext.tsx
- database-client/__tests__/passportScorerClient.test.ts
- database-client/src/passportScorerClient.ts
- types/src/index.d.ts
> feat(app): patch stamps instead of separate delete + add

- platforms/src/ETH/Providers/ethErc20Possession.ts
- platforms/src/ETH/__tests__/ethErc20PossessionEth.test.ts
- platforms/src/Ens/Providers/EnsProvider.ts
- platforms/src/Ens/__tests__/EnsProvider.test.ts
- platforms/src/GTC/__tests__/ethErc20PossessionGtc.test.ts
- platforms/src/NFT/Providers/__tests__/nft.test.ts
- platforms/src/NFT/Providers/nft.ts
fixes #1371 
Changes explained in associated ticket
> 1371 backend alchemy efficiency

- platforms/src/ZkSync/App-Bindings.ts
> fix(app): update zksync banner

- platforms/src/Linkedin/Providers/linkedin.ts
- platforms/src/Linkedin/__tests__/linkedin.test.ts
> chore(platforms): update deprecated linkedin endpoint

- app/components/GenericPlatform.tsx
- app/pages/Dashboard.tsx
- app/pages/_app.tsx
adds google tag manager interaction duration event and verification button class
fixes: https://github.com/gitcoinco/passport/issues/1421
> chore(app): adds google tag manager interaction duration event

- app/pages/_app.tsx
Closes: https://github.com/gitcoinco/passport/issues/1421
> chore(app): adds review environment auth and env

- app/components/NoStampModal.tsx
fixes: https://github.com/gitcoinco/passport/issues/1386
> chore(app): adds close button to 'Verification Failed' modal

- app/__tests__/components/ExpiredStampModal.test.tsx
- app/context/ceramicContext.tsx
- platforms/src/platforms.ts
> chore(app, platforms): feature flag poap stamp

- app/context/scorerContext.tsx
- iam/package.json
- package.json
> 1400 rescoring

- platforms/src/Lens/Providers/lens.ts
- platforms/src/Lens/__tests__/lens.test.ts
> refactor(platforms): update data that is hashed for lens profile

- infra/production/index.ts
- infra/review/index.ts
- infra/staging/index.ts
- platforms/src/Civic/App-Bindings.ts
> fix(api): fixed scope selection and added env var to infra files

- iam/.env-example.env
- infra/production/index.ts
- infra/review/index.ts
- infra/staging/index.ts
- platforms/jest.config.js
- platforms/src/ZkSync/Providers/zkSyncEra.ts
- platforms/src/ZkSync/__tests__/zkSyncEra.test.ts
- platforms/testSetup.js
fixes: https://github.com/gitcoinco/passport/issues/1438
> fix(platforms, iam): adds working api endpoint

- platforms/src/GuildXYZ/Providers/guildXYZ.ts
- platforms/src/GuildXYZ/__tests__/guildXYZ.test.ts
fixes: #[1075](https://github.com/gitcoinco/passport/issues/1075)
> fix(platforms): caseing issue for guild endpoint

- iam/.env-example.env
- infra/production/index.ts
- infra/review/index.ts
- infra/staging/index.ts
- platforms/src/Gitcoin/Providers/__tests__/gitcoinGrantsContributorStatistics.test.ts
- platforms/src/Gitcoin/Providers/__tests__/gitcoinGrantsGranteeStatistics.test.ts
- platforms/src/Gitcoin/Providers/__tests__/gitcoinGrantsStatistics.test.ts
- platforms/src/Gitcoin/Providers/gitcoinGrantsContributorStatistics.ts
- platforms/src/Gitcoin/Providers/gitcoinGrantsGranteeStatistics.ts
- platforms/src/Gitcoin/Providers/gitcoinGrantsStatistics.ts
fixes https://github.com/gitcoinco/passport-scorer/issues/289
> feat(platforms): pointing to the new endpoint for cgrants data

- platforms/src/Gitcoin/App-Bindings.ts
> chore(app): update gitcoin stamp banner

- app/components/SyncToChainButton.tsx
- app/pages/Dashboard.tsx
fixes: https://github.com/gitcoinco/passport/issues/1480
> feat(app): adds go on-chain button

- app/components/OnChainTag.tsx
- app/components/PlatformCard.tsx
- app/components/StampSelector.tsx
fixes: https://github.com/gitcoinco/passport/issues/1483
> feat(app): adds on-chain stamp label

- app/pages/Dashboard.tsx
> feat(app): updating threshold in tooltip

- iam/Dockerfile
> fix(iam): using updated CMD in dockerfile

- platforms/src/Twitter/Providers/twitterAccountAge.ts
- platforms/src/Twitter/procedures/twitterOauth.ts
fixes: https://discord.com/channels/562828676480237578/1135967806060494981
> Clear text twitter fix

- app/components/SupportBanner.tsx
- app/components/Warning.tsx
- app/context/userContext.tsx
> 1490 warning update

- platforms/src/Gitcoin/Providers/__tests__/gitcoinGrantsStatistics.test.ts
- platforms/src/Gitcoin/Providers/gitcoinGrantsStatistics.ts
This fixes: https://github.com/gitcoinco/passport/issues/1534
> feat(iam,gitcoin): query the cgrants API in the scorer by the github id

- app/__tests__/context/ceramicContext.test.tsx
- app/context/ceramicContext.tsx
> fix(app): filter out expired stamps from provider state

- platforms/src/GtcStaking/Providers-config.ts
closes: https://github.com/gitcoinco/passport/issues/1583
> chore(platforms): updates staking verbiage

- platforms/src/Hypercerts/Providers/Hypercerts.ts
- platforms/src/Hypercerts/Providers/__tests__/Hypercerts.test.ts
adds error messaging to hypercerts
https://github.com/gitcoinco/passport/issues/1598
> chore(platforms): add error message to hypercert issuance

- platforms/src/Twitter/Providers/__tests__/twitterAccountAge.test.ts
- platforms/src/Twitter/procedures/twitterOauth.ts
- platforms/src/procedure-router.ts
> feat(platforms): added optional Twitter callback override

- deployments/onchainInfo.json
> feat(infra): added OP contract deployment using production issuer

- app/__tests__/components/SyncToChainButton.test.tsx
- app/components/OnchainSidebar.tsx
- app/components/OnchainTag.tsx
- app/components/PlatformCard.tsx
- app/components/StampSelector.tsx
- app/components/SyncToChainButton.tsx
- app/context/onChainContext.tsx
- app/utils/onChainStamps.ts
> chore(app): updated onchain sidebar text, made syntax consistent

- platforms/src/Twitter/procedures/twitterOauth.ts
fixes: https://github.com/gitcoinco/passport/issues/1622
> fix(platforms): adds scope to twitter auth flow

- platforms/src/GuildXYZ/Providers/guildXYZ.ts
fixes: https://github.com/gitcoinco/passport/issues/1595
> fix(platforms): updates to return with variable

- platforms/src/Gitcoin/App-Bindings.ts
- platforms/src/GrantsStack/App-Bindings.ts
> feat(app): update Gitcoin & GrantsStack stamps notes

- iam/__tests__/index.test.ts
- iam/src/index.ts
- iam/src/utils/scorerService.ts
- infra/production/index.ts
- platforms/src/TrustaLabs/Providers/TrustaLabs.ts
- platforms/src/index.ts
- platforms/src/utils/handleAxiosError.ts
- platforms/src/utils/handleProviderAxiosError.ts
> fix(iam,infra): add more detailed errors to /eas requests, increase iam task size and disable scaling

- platforms/src/Civic/App-Bindings.ts
> feat(platforms): civic stamp - add fantom support

- app/package.json
- app/utils/onboard.ts
> feat(app): enable WalletConnect V2 for ledger module in Web3Connect

- app/utils/chains.ts
> chore(app): update polygon rpc

- platforms/src/Idena/__tests__/signin.test.ts
- platforms/src/TrustaLabs/Providers/TrustaLabs.ts
fixes https://github.com/gitcoinco/passport/issues/1629
> feat(api): storing additional trustalabs score details

- app/__tests__/pages/Home.test.tsx
- app/components/Button.tsx
- app/components/CardList.tsx
- app/components/Checkbox.tsx
- app/components/Footer.tsx
- app/components/Header.tsx
- app/components/JsonOutputModal.tsx
- app/components/OnchainSidebar.tsx
- app/components/PageRoot.tsx
- app/components/ProcessingPopup.tsx
- app/components/RefreshMyStampsModal.tsx
- app/components/RefreshMyStampsModalContent.tsx
- app/components/RefreshMyStampsModalContentCard.tsx
- app/components/RefreshMyStampsSelector.tsx
- app/components/RefreshStampsProgressSteps.tsx
- app/components/Toggle.tsx
- app/components/Warning.tsx
- app/components/WelcomeWrapper.tsx
- app/pages/Dashboard.tsx
- app/pages/Home.tsx
- app/pages/Maintenance.tsx
- app/pages/Welcome.tsx
- app/pages/privacy.tsx
- app/tailwind.config.js
- app/utils/theme/chakra/Menu.tsx
- app/utils/theme/chakra/Modal.tsx
- app/utils/theme/palette.tsx
- app/utils/theme/setTheme.tsx
- app/utils/theme/themes.tsx
- app/utils/theme/types.tsx
fixes https://github.com/gitcoinco/passport/issues/1688
fixes #1693
> feat(app): implement new theme and basic dashboard layout

- app/components/CardList.tsx
- app/components/PlatformCard.tsx
> fix(app): account for sybil wallets

- app/__test-fixtures__/contextTestHelpers.tsx
- app/__tests__/pages/Home.test.tsx
- app/components/ExpiredStampsPanel.tsx
- app/context/userContext.tsx
- app/pages/Home.tsx
> 1723 inconsistent display

- platforms/src/Github/Providers/__tests__/githubAccountCreation.test.ts
- platforms/src/Idena/Providers/IdenaAgeProvider.ts
- platforms/src/Idena/Providers/IdenaStakeProvider.ts
- platforms/src/Idena/Providers/IdenaStateProvider.ts
- platforms/src/Idena/__tests__/provider.test.ts
- platforms/src/Idena/procedures/idenaSignIn.ts
- platforms/src/utils/providers.ts
> feat(platforms): add failure reasons to idena stamps

- app/__tests__/components/NetworkCard.test.tsx
- app/__tests__/components/SyncToChainButton.test.tsx
- app/components/Button.tsx
- app/components/InitialWelcome.tsx
- app/components/NetworkCard.tsx
- app/components/RefreshMyStampsModal.tsx
- app/components/RefreshMyStampsModalContent.tsx
- app/components/RefreshMyStampsModalContentCard.tsx
- app/components/SyncToChainButton.tsx
- app/components/VeraxPanel.tsx
- app/components/WelcomeBack.tsx
- app/hooks/useDashboardCustomization.tsx
- app/hooks/useOnChainStatus.tsx
- app/hooks/useSyncToChainButton.tsx
- app/pages/Dashboard.tsx
- app/pages/Home.tsx
- app/pages/Welcome.tsx
- app/pages/index.tsx
- app/tailwind.config.js
- app/utils/theme/palette.tsx
- app/utils/theme/setTheme.tsx
- app/utils/theme/themes.tsx
- app/utils/theme/types.tsx
> feat(app): added ability to specify custom dashboard, added verax customization

- app/__tests__/components/AttestationProvider.test.tsx
- app/__tests__/components/NetworkCard.test.tsx
- app/components/InitiateOnChainButton.tsx
- app/context/onChainContext.tsx
- app/hooks/useOnChainStatus.tsx
- app/hooks/useSyncToChainButton.tsx
- app/utils/AttestationProvider.ts
- app/utils/onChainStamps.ts
- iam/__tests__/easPassportSchema.test.ts
- iam/__tests__/index.test.ts
- iam/__tests__/index_eas_score.test.ts
- iam/src/index.ts
- iam/src/utils/easPassportSchema.ts
- types/src/index.d.ts
Fixes: https://github.com/gitcoinco/passport/issues/1809
> 1809 update verax implementation

- iam/src/main.ts
- infra/production/index.ts
- infra/staging/index.ts
> feat(infra): lowering IAM server size, increaing keepalive timeout for better stability

- app/components/VeraxPanel.tsx
Fixes: https://github.com/gitcoinco/passport/issues/1829
> fix(app,language): fixing language for Verax dashboard

- app/__tests__/components/SyncToChainButton.test.tsx
- app/components/NetworkCard.tsx
- app/components/OnchainSidebar.tsx
- app/components/SyncToChainButton.tsx
- app/utils/chains.ts
> feat(app): update on chain sidebar styling

- iam/src/index.ts
> fix(iam): match case for id and recipient

- platforms/src/Gitcoin/App-Bindings.ts
- platforms/src/Gitcoin/Providers-config.ts
> fix(platforms): updated gitcoin grants stamp banner

- platforms/src/Ens/Providers/EnsProvider.ts
- platforms/src/Ens/__tests__/EnsProvider.test.ts
> feat(platforms): restrict ENS stamp to only ENS names using the public resolver

- app/__test-fixtures__/contextTestHelpers.tsx
- app/__tests__/context/userContext.test.tsx
- app/__tests__/pages/Home.test.tsx
- app/context/userContext.tsx
- app/pages/Dashboard.tsx
- app/pages/Home.tsx
> feat(app): require user to click SIWE button to request signature

- app/components/PlatformCard.tsx
- app/components/PlatformDetails.tsx
> fix(app): fixed Available Points display for modified stamps

- platforms/src/GtcStaking/Providers/GtcStaking.ts
fixes: https://github.com/gitcoinco/passport/issues/1869
> fix(platforms): fixes experienced community staking stamp bug

- iam/Dockerfile
Fix: https://github.com/gitcoinco/passport/issues/1862
> fix: node version in iam/Dockerfile

- app/next.config.js
- iam/Dockerfile
- change node version in iam/Dockerfile to 18
- change export command to `yarn build` as indicated here: https://nextjs.org/docs/pages/building-your-application/deploying/static-exports
This fixes: https://github.com/gitcoinco/passport/issues/1862
> fix: fix node version & export

- platforms/src/Ens/Providers/EnsProvider.ts
- platforms/src/Ens/__tests__/EnsProvider.test.ts
> fix(platforms): added old ENS public resolver to list of legit public resolvers

- app/__tests__/components/SupportBanner.test.tsx
- app/components/Header.tsx
- app/components/SupportBanner.tsx
- app/components/Warning.tsx
- app/hooks/useSupportBanners.tsx
> feat(app): new banner designs

- platforms/src/GtcStaking/Providers/GtcStaking.ts
- platforms/src/GtcStaking/Providers/communityStaking.ts
- platforms/src/GtcStaking/Providers/selfStaking.ts
- platforms/src/GtcStaking/__tests__/communityStaking.test.ts
- platforms/src/GtcStaking/__tests__/selfStaking.test.ts
fixes https://github.com/gitcoinco/passport/issues/1819
> feat(platforms): updated GTC stake provider to use new API response

- platforms/src/NFT/Providers/__tests__/nft.test.ts
- platforms/src/NFT/Providers/nft.ts
> feat(platforms): deduping NFT stamp based on token contract and id

- platforms/src/CyberProfile/App-Bindings.ts
- platforms/src/CyberProfile/Providers-config.ts
- platforms/src/CyberProfile/Providers/cyberconnect.ts
- platforms/src/CyberProfile/__tests__/cyberconnect.test.ts
- platforms/src/Idena/Providers/IdenaStakeProvider.ts
- platforms/src/Idena/Providers/IdenaStateProvider.ts
- platforms/src/Idena/__tests__/provider.test.ts
> feat(platforms): making higher tier credentials inclusive of lower tier credentials

- .github/workflows/iam-promote-staging.yml
- infra/aws/index.ts
This fixes https://github.com/gitcoinco/passport/issues/1873
> 1873 deploy passport to staging via new infra

- infra/aws/index.ts
Fixes: https://github.com/gitcoinco/passport/issues/1944
> fix(infra): fix getting redisConnectionUrl from core infra

- infra/aws/iam_secrets.ts
- infra/aws/index.ts
Fixes: https://github.com/gitcoinco/passport/issues/1944
> fix(infra): proper container definition with _redisConnectionUrl

- app/components/VeraxPanel.tsx
- app/utils/theme/chakra/Modal.tsx
- iam/src/index.ts
> feat(app): on Verax panel, confirm before submit if score low

- platforms/src/Coinbase/App-Bindings.tsx
> feat(platforms): updated Coinbase stamp info with reference to onchain attestations

- platforms/src/Civic/Providers/civic.ts
- platforms/src/Civic/Providers/util.ts
- platforms/src/Civic/__tests__/civic.test.ts
> feat(platforms): retrieve expired civic passes and alert user if expired

- platforms/src/Lens/Providers/lens.ts
- platforms/src/Lens/__tests__/lens.test.ts
> fix(platforms): update lens provider to v2 api

- app/context/stampClaimingContext.tsx
> fix:(app): set initial refresh state to idle to allow user inititaion

- .github/workflows/ci.yml
- app/package.json
- app/utils/onboard.ts
- yarn.lock
fixes: https://twitter.com/Ledger/status/1735291427100455293
> fix(app): remove ledge connect lilbrary

- platforms/src/NFT/Providers-config.ts
- platforms/src/NFT/Providers/__tests__/nft.test.ts
- platforms/src/NFT/Providers/nft.ts
> feat(platforms): refactor nft stamp to exclude erc1155

- platforms/src/Civic/Providers/civic.ts
- platforms/src/Civic/__tests__/civic.test.ts
Fixes https://github.com/gitcoinco/passport/issues/1963
> fix(platforms): remove '90 day' reference from civic error message

- platforms/src/Civic/Providers/civic.ts
- platforms/src/Civic/Providers/types.ts
- platforms/src/Civic/Providers/util.ts
- platforms/src/Civic/__tests__/civic.test.ts
fixes #1963 
needs rebase after https://github.com/gitcoinco/passport/pull/2009 is merged b/c this includes those commits
> 1963 civic active

- app/__tests__/pages/Dashboard.test.tsx
- app/context/ceramicContext.tsx
- app/pages/Dashboard.tsx
> feat(ui): replacing inaccurate 'loading from ceramic' message with 'initializing passport'

- database-client/integration-tests/ceramicDatabaseTest.ts
- platforms/src/ETH/App-Bindings.ts
- platforms/src/ETH/Providers-config.ts
> chore(platforms): update copy remove debugger

- database-client/src/composeDatabase.ts
fixes: https://github.com/gitcoinco/passport/issues/2065
> fix[databse-client]: logging messages to debug issues writing to compose

- iam/Dockerfile
fixes: https://github.com/gitcoinco/passport/issues/2065
> fix[iam]: fix node version in iam/Dockerfile

- app/__tests__/context/ceramicContext.test.tsx
- app/context/ceramicContext.tsx
- database-client/__tests__/composeDatabase.test.ts
- database-client/integration-tests/ceramicDatabaseStampValidity.ts
- database-client/integration-tests/ceramicDatabaseTest.ts
- database-client/src/composeDatabase.ts
- database-client/src/passportScorerClient.ts
- database-client/src/types.ts
- types/src/index.d.ts
> feat(app): writing compose DB status to the scorer backend

- database-client/src/composeDatabase.ts
fixes: https://github.com/gitcoinco/passport/issues/2065
> feat(database-client): add logging to trace execution

- platforms/src/Holonym/Providers/holonymGovIdProvider.ts
- platforms/src/Holonym/__tests__/holonymGovId.test.ts
Fixes: https://github.com/gitcoinco/passport/issues/2071
> chore(platforms): use holonym api instead of contract

- platforms/src/ETH/App-Bindings.ts
- platforms/src/ETH/Providers-config.ts
Fixes: https://github.com/gitcoinco/passport/issues/2080
> fix[platforms,ETH]: updating text & links for ETH stamp

- .github/workflows/ci.yml
- js-ceramic/Dockerfile
- js-ceramic/README.md
- js-ceramic/ceramic/daemon.config.json
fixes: https://github.com/gitcoinco/passport/issues/2060
> fix[ci]: deploy ceramic models before running integration tests

- app/context/datastoreConnectionContext.tsx
Fixes: https://github.com/gitcoinco/passport/issues/2086
> 2086 debug multiformats 4

- app/context/datastoreConnectionContext.tsx
Fixes: https://github.com/gitcoinco/passport/issues/2086
> fix[app]: switch datadogRum.addError -> datadogLogs.logger.warn

- app/context/scorerContext.tsx
> fix(app): removed infinite loop glitch triggered by a failed get score request

- app/__test-fixtures__/contextTestHelpers.tsx
- app/__tests__/components/GenericPlatform.test.tsx
- app/__tests__/context/ceramicContext.test.tsx
- app/components/GenericPlatform.tsx
- app/context/ceramicContext.tsx
- app/context/datastoreConnectionContext.tsx
fixes https://github.com/gitcoinco/passport/issues/2141
> feat(app): checking for expired did sessions

- iam/package.json
- yarn.lock
Fixes: https://github.com/gitcoinco/passport/issues/2164
> fix[iam]: upgrading "moralis": "^2.24.2"

- platforms/src/GtcStaking/Providers-config.ts
Fixes: https://github.com/gitcoinco/passport/issues/2137
> make the gtc community staking tier 2 requrimenet clearer

- iam/src/index.ts
fixes: https://github.com/gitcoinco/passport/issues/2177
> fix[iam]: accept eip712 issuer in /passport request

- app/__tests__/hooks/useDashboardCustomization.test.tsx
- app/components/CustomDashboardPanel.tsx
- app/components/SIWEButton.tsx
- app/components/TestingPanel.tsx
- app/components/VeraxPanel.tsx
- app/hooks/useDashboardCustomization.tsx
- app/pages/Dashboard.tsx
- app/pages/Home.tsx
- app/tailwind.config.js
- app/utils/customizationUtils.tsx
- app/utils/theme/palette.tsx
- app/utils/theme/setCustomizationTheme.tsx
- app/utils/theme/types.tsx
- yarn.lock
> feat(app): enabling dynamically defined dashboard customizations

- platforms/src/Civic/App-Bindings.tsx
> feat(platforms): adding more info to Civic sidebar

- platforms/src/Civic/App-Bindings.tsx
> fix(platforms): fix new civic link

- .github/workflows/iam-cd-review.yml
- .github/workflows/iam-promote-production.yml
- .github/workflows/iam-promote-staging.yml
Fixes: https://github.com/gitcoinco/passport/issues/2210
> fix(infra): caching node ressource for pulumi stack

- .github/workflows/iam-promote-production.yml
Fixes: https://github.com/gitcoinco/passport/issues/2210
> fix(infra): stack name for production

- infra/aws/index.ts
- infra/lib/staking/app.ts
- infra/package.json
- infra/yarn.lock
Fixes: https://github.com/gitcoinco/passport/issues/2210
> fat(infra): creating hook for amplify app to trigger rebuilds

- platforms/src/GtcStaking/Providers/GtcStaking.ts
- platforms/src/GtcStaking/Providers/communityStaking.ts
- platforms/src/GtcStaking/__tests__/communityStaking.test.ts
- platforms/src/GtcStaking/__tests__/selfStaking.test.ts
This fixes https://github.com/gitcoinco/passport/issues/2310
> 2310 id staking v2

- platforms/src/GtcStaking/Providers/communityStaking.ts
- platforms/src/GtcStaking/__tests__/communityStaking.test.ts
This fixes https://github.com/gitcoinco/passport/issues/2348
> feat(GtcStaking): fix TrustedCitizen stamp(#2310)

- infra/aws/index.ts
Fixes: https://github.com/gitcoinco/passport/issues/2361
> feat(infra,staking): adding env vars for staking app deployment

- app/components/DashboardScorePanel.tsx
- app/components/PlatformCard.tsx
- app/components/StampSelector.tsx
- app/context/scorerContext.tsx
- app/pages/Dashboard.tsx
- app/utils/customizationUtils.tsx
- yarn.lock
fixes https://github.com/gitcoinco/passport/issues/2364
> feat(app): allow customizing scorer title, fixed filtering and rescoring issues

- app/components/DashboardScorePanel.tsx
- app/utils/customizationUtils.tsx
fixes https://github.com/gitcoinco/passport/issues/2364
> feat(app): allow customization of scorer panel text

- app/context/ceramicContext.tsx
- platforms/src/Coinbase/App-Bindings.tsx
> feat(platforms): adding link to coinbase stamp docs

- platforms/src/ETH/Providers/accountAnalysis.ts
- platforms/src/ZkSync/Providers-config.ts
- platforms/src/ZkSync/Providers/accountAnalysis.ts
- platforms/src/ZkSync/__tests__/accountAnalysis.test.ts
- types/src/index.d.ts
> feat(platforms): added zksync model providers

- platforms/src/ZkSync/App-Bindings.ts
> feat(platforms): added doc link, updated wording in zksync sidebar

- platforms/src/NFT/App-Bindings.ts
- platforms/src/NFT/Providers-config.ts
Needs to be rebased after https://github.com/gitcoinco/passport/pull/2387 merged
Potentially still need to change the "Learn More" link, pending feedback in ticket.
fixes #2381
> feat(platforms): added doc link, updated wording in nft sidebar

- app/__test-fixtures__/contextTestHelpers.tsx
- platforms/src/ETH/Providers-config.ts
- platforms/src/ETH/Providers/accountAnalysis.ts
- platforms/src/ETH/__tests__/accountAnalysis.test.ts
- types/src/index.d.ts
fixes #2331 
Should be merged AFTER https://github.com/gitcoinco/passport/pull/2389, and then this should be rebased onto main to remove the duplicate commit.
> feat(platforms): updating eth stamp to use v2 model

- platforms/src/ETH/Providers/accountAnalysis.ts
> fix(platforms): fixing eth model URL

- iam/src/static/providerBitMapInfo.json
Fixes: https://github.com/gitcoinco/passport/issues/2331
> feat(app,iam): updating providerBitMapInfo.json

- README.md
Remove bug bounty reference from readme
@erichfi 
Fixes: https://github.com/gitcoinco/passport/issues/2423
> feat: remove bug bounty info

- .github/workflows/release_and_deploy_passport.yml
- infra/aws/index.ts
- infra/lib/staking/app.ts
- infra/package.json
- infra/yarn.lock
This fixes https://github.com/gitcoinco/passport/issues/2372
> feat(infra): manage cloudflare domain for production

- platforms/src/ZkSync/Providers-config.ts
- platforms/src/ZkSync/Providers/accountAnalysis.ts
This fixes https://github.com/gitcoinco/passport/issues/2429
> feat(zkSync): migrate to V2 of the model

- infra/lib/staking/app.ts
This fixes https://github.com/gitcoinco/passport/issues/2429
> feat(infra): fix record name for certificate validation

- platforms/src/Coinbase/App-Bindings.tsx
- platforms/src/Coinbase/Providers-config.ts
Fixes: https://github.com/gitcoinco/passport/issues/2461
> feat(platforms): updating coinbase stamp text

- app/components/NetworkCard.tsx
- app/utils/AttestationProvider.ts
- app/utils/chains.ts
Fixes: https://github.com/gitcoinco/passport/issues/2446
> feat(app): show link to Verax explorer for Linea

- app/context/scorerContext.tsx
Fixes: https://github.com/gitcoinco/passport/issues/2477
> feat(app): add support for raw scores from non-binary scorers as well

- app/components/DashboardScorePanel.tsx
- app/hooks/useOneClickVerification.tsx
> 2089 follow up

- infra/aws/index.ts
This fixes https://github.com/gitcoinco/passport/issues/2511
> update amplify envs

- infra/aws/index.ts
Fixes: https://github.com/gitcoinco/passport/actions/runs/9310185985/job/25627310667
> fix(infra): fix env config

- infra/aws/index.ts
Fixes: https://github.com/gitcoinco/passport/issues/2550
> feat: disable passport protection for staking app

- infra/aws/index.ts
> fix(infra): only default to 2 tasks in prod

- app/utils/chains.ts
This fixes https://github.com/gitcoinco/passport/issues/2125
> feat(chains): remove public goods network

- app/components/WelcomeFooter.tsx
- app/components/WelcomeWrapper.tsx
- app/package.json
- app/pages/Home.tsx
- yarn.lock
This fixes : https://github.com/gitcoinco/passport/issues/2563
> feat(ui): update onboarding flow for mobile

- app/components/Category.tsx
This fixes https://github.com/gitcoinco/passport/issues/2437
> feat(ui): add cursor hover for stamp category

- app/__tests__/components/GenericPlatform.test.tsx
- app/__tests__/components/SideBarContent.test.tsx
- app/__tests__/components/StampSelector.test.tsx
- app/components/Category.tsx
- app/components/GenericBanner.tsx
- app/components/GenericPlatform.tsx
- app/components/LoadButton.tsx
- app/components/PlatformDetails.tsx
- app/components/SideBarContent.tsx
- app/components/Spinner.tsx
- app/components/StampSelector.tsx
- app/styles/globals.css
- app/tailwind.config.js
- app/utils/theme/palette.tsx
- app/utils/theme/setTheme.tsx
- app/utils/theme/themes.tsx
- app/utils/theme/types.tsx
> 2455 sidebar

- platforms/package.json
- platforms/src/GuildXYZ/Providers/guildXYZ.ts
- platforms/src/GuildXYZ/__tests__/guildXYZ.test.ts
- yarn.lock
> fix(platforms): switching to new Guild SDK

- platforms/src/GuildXYZ/Providers/guildXYZ.ts
fixes https://github.com/gitcoinco/passport/issues/2582
> fix(platforms): remove console.log accidentally left in from development

- app/context/ceramicContext.tsx
This fixes https://github.com/gitcoinco/passport/issues/2605
> Stam removal update

- platforms/src/AllowList/Providers/allowList.ts
- platforms/src/AllowList/__tests__/allowList.test.ts
Fixes: https://github.com/gitcoinco/passport/issues/2604
> chore(app, platforms): moved allow list endpoint

- platforms/src/AllowList/Providers/allowList.ts
> chore: add api key

- app/components/GenericBanner.tsx
- app/components/InitiateReverifyStampsButton.tsx
- app/components/NetworkCard.tsx
- app/components/Warning.tsx
- app/pages/Maintenance.tsx
- app/tailwind.config.js
- platforms/src/Civic/App-Bindings.tsx
- platforms/src/Coinbase/App-Bindings.tsx
- platforms/src/Gitcoin/App-Bindings.tsx
- platforms/src/GtcStaking/App-Bindings.tsx
- platforms/src/TrustaLabs/App-Bindings.tsx
- platforms/src/index.ts
- platforms/src/utils/Hyperlink.tsx
fixes https://github.com/gitcoinco/passport/issues/2544
> feat(app,platforms): created common Hyperlink component

- infra/aws/index.ts
Fixes: https://github.com/gitcoinco/passport/issues/2593
> feat: add NEXT_PUBLIC_MAX_LEGACY_ROUND_ID to the staking apps env vars

- app/__tests__/components/DashboardScorePanel.test.tsx
- app/__tests__/components/OnChainSidbar.test.tsx
- app/__tests__/config/providers.test.ts
- app/__tests__/hooks/useCustomization.test.tsx
- app/components/CardList.tsx
- app/components/Category.tsx
- app/components/CustomDashboardPanel.tsx
- app/components/DashboardScorePanel.tsx
- app/components/OnchainSidebar.tsx
- app/components/PlatformCard.tsx
- app/components/PlatformDetails.tsx
- app/components/StampSelector.tsx
- app/config/providers.ts
- app/context/ceramicContext.tsx
- app/context/scorerContext.tsx
- app/hooks/useCustomization.tsx
- app/utils/chains.ts
- app/utils/customizationUtils.tsx
> feat(app): is custom chain ids are returned filter displayed chains

- app/context/datastoreConnectionContext.tsx
Fixes: https://github.com/gitcoinco/passport/issues/2642
> feat: adding debug statements for review

- infra/aws/index.ts
This fixes https://github.com/gitcoinco/passport/issues/2640
> feat(infra): modify ALB rule priority number

- app/components/GenericBanner.tsx
- app/components/PlatformDetails.tsx
Fixes: https://github.com/gitcoinco/passport/issues/2653
> fix: restoring sidebar content

- infra/aws/index.ts
This fixes https://github.com/gitcoinco/passport/issues/2640
> feat(infra): modify stack outputs

- platforms/src/Linkedin/Providers/linkedin.ts
- platforms/src/Linkedin/__tests__/linkedin.test.ts
> fix: linkedin api version increment

- app/components/CardList.tsx
Fixes: https://github.com/gitcoinco/passport/issues/2601
> feat: adding Outdid stamp to 'Government IDs' category

- app/pages/Dashboard.tsx
This fixes https://github.com/gitcoinco/passport/issues/2660
> feat(deashboard): remove my stamps

- platforms/src/Outdid/App-Bindings.ts
Reference for safari specific error
https://stackoverflow.com/questions/20696041/window-openurl-blank-not-working-on-imac-safari
Fixes: https://github.com/gitcoinco/passport/issues/2693
> fix(platforms): open window before async call

- app/components/GenericPlatform.tsx
> fix(app): dropping 'removed stamps' verification statuses that no longer apply

- platforms/src/Binance/App-Bindings.tsx
> feat: binance help

- platforms/src/Outdid/App-Bindings.ts
> chore(platforms): added outdid guide link

- .github/actions/deploy_to_aws/action.yml
- .github/actions/prepare_deploy_to_aws/action.yml
- .github/workflows/build_and_deploy_generic.yml
- .github/workflows/build_and_deploy_review.yml
This fixes https://github.com/gitcoinco/passport/issues/2684
> feat(infra): add new workflow for review

- .github/actions/deploy_to_aws/action.yml
- .github/workflows/build_and_deploy_generic.yml
- .github/workflows/build_and_deploy_production.yml
- .github/workflows/build_and_deploy_staging.yml
- .github/workflows/deploy_generic.yml
- .github/workflows/deploy_production.yml
- .github/workflows/deploy_review.yml
- .github/workflows/deploy_staging.yml
- .github/workflows/release_and_deploy_production.yml
This fixes https://github.com/gitcoinco/passport/issues/2684
> add generic deploy & stg - prd workflows for testing

- platforms/src/Holonym/App-Bindings.tsx
- platforms/src/Holonym/Providers-config.ts
> chore(platforms): updating Holonym sidebar info

- database-client/src/composeDatabase.ts
> feat(app): issue datadog info message when adding/deleting individual stamps

- app/components/Notifications.tsx
> fix: bell icon overflow

- platforms/src/Outdid/App-Bindings.tsx
- platforms/src/Outdid/Providers-config.ts
> feat(platforms): updating Outdid sidebar

- app/pages/index.tsx
Fixes: https://github.com/passportxyz/passport/issues/2755
> feat: allow datadogRum sample rate to be configured through env vars

- platforms/src/Outdid/App-Bindings.tsx
> fix(app): fix mismatch in description

- app/__tests__/components/CardList.test.tsx
- app/components/PlatformCard.tsx
- app/components/PlatformDetails.tsx
- app/components/StampSelector.tsx
- app/context/scorerContext.tsx
Fixes: https://github.com/passportxyz/passport/issues/2701
> 2701 rounded

- app/__tests__/components/AttestationProvider.test.tsx
- app/utils/AttestationProvider.ts
> feat(app): pushing full Passport to Linea

- app/components/CancelButton.tsx
- app/components/OnchainSidebar.tsx
- app/components/SideBarContent.tsx
- app/utils/theme/chakra/Drawer.tsx
- app/utils/theme/themeWrapper.tsx
> 2733 close mechanism

- app/components/AccountCenter.tsx
> feat(app): never show eth balance in account center

- app/components/Confetti.tsx
> fix(app): modify confetti dimensions on window resize

- app/components/InitialWelcome.tsx
- app/components/WelcomeFooter.tsx
- app/components/WelcomeWrapper.tsx
- app/pages/Dashboard.tsx
- app/pages/Home.tsx
- app/pages/Welcome.tsx
Fixes: https://github.com/passportxyz/passport/issues/2779
> feat: have adjusted Home screen according to the designs

- .github/workflows/build_and_deploy_generic.yml
- .github/workflows/deploy_generic.yml
> feat(infra): updating pulumi org name

- app/__tests__/pages/Dashboard.test.tsx
- app/components/Confetti.tsx
- app/components/GenericPlatform.tsx
- app/components/PassportDetailsButton.tsx
- app/components/Spinner.tsx
- app/components/SyncToChainButton.tsx
- app/components/WelcomeFooter.tsx
- app/pages/Dashboard.tsx
- app/pages/_app.tsx
- yarn.lock
> feat(app): added details (json) button, fixed lint warnings

- app/components/DoneToastContent.tsx
- app/components/GenericPlatform.tsx
- app/components/InitiateReverifyStampsButton.tsx
- app/components/RemoveStampModal.tsx
- app/context/ceramicContext.tsx
- app/context/stampClaimingContext.tsx
- app/hooks/useBreakpoint.tsx
- app/hooks/useLoginFlow.tsx
- app/hooks/useMessage.tsx
- app/hooks/useOneClickVerification.tsx
- app/hooks/useSyncToChainButton.tsx
- app/pages/Dashboard.tsx
- app/tailwind.config.ts
> feat(app): updating message handler, moving to top on small screen

- infra/aws/index.ts
- platforms/src/Linkedin/App-Bindings.ts
this fixes https://github.com/passportxyz/passport/issues/2767
> 2767 passport.xyz migration

- platforms/src/Github/Providers-config.ts
- platforms/src/Github/Providers/__tests__/githubClient.test.ts
- platforms/src/Github/Providers/__tests__/githubContributionActivity.test.ts
- platforms/src/Github/Providers/githubClient.ts
- platforms/src/Github/Providers/githubContributionActivity.ts
> feat(platforms): updating github stamp to check that contributions happen after repo creation

- app/__tests__/hooks/useCustomization.test.tsx
- app/__tests__/pages/Dashboard.test.tsx
- app/jest.setup.ts
- app/pages/Dashboard.tsx
- app/utils/customizationUtils.tsx
> feat: hide/show explanation based customization config

- app/components/Confetti.tsx
> feat: fix confetti height

- app/components/CardList.tsx
- app/components/Category.tsx
- app/components/Confetti.tsx
- app/components/PlatformCard.tsx
- app/hooks/usePlatforms.ts
- app/public/assets/dev-icon.svg
- platforms/src/CustomGithub/Providers-config.ts
> feat(app): adding card variant for custom stamps

- app/__tests__/hooks/usePlatforms.test.ts
- app/config/platformMap.ts
> feat(app): added tests for usePlatforms

- app/components/NetworkCard.tsx
- app/hooks/useOnChainData.tsx
- app/package.json
- deployments/onchainInfo.json
- yarn.lock
Fixes: #2844 
[This](https://github.com/ethers-io/ethers.js/issues/3835) error was being thrown when the transaction was being read. Upgrading ethers appears to resolve it.
> 2844 sidebar bug

- app/pages/Home.tsx
> fix(app): home page alignment

- app/components/WelcomeFooter.tsx
fixes https://github.com/passportxyz/passport/issues/2903
> fix(app): correcting repo link

- app/__tests__/components/DashboardScorePanel.test.tsx
- app/__tests__/components/ExpiredStampsPanel.test.tsx
- app/components/DashboardScorePanel.tsx
- app/components/ExpiredStampsPanel.tsx
- app/components/PlatformCard.tsx
- app/components/PlatformDetails.tsx
Fixes: https://github.com/passportxyz/passport/issues/2881
> fix: audit spelling of Stamp and Passport

- app/hooks/useSyncToChainButton.tsx
- app/utils/chains.ts
- iam/__tests__/scorerService.test.ts
- iam/src/index.ts
- iam/src/utils/easPassportSchema.ts
- iam/src/utils/scorerService.ts
- types/src/index.d.ts
> feat: custom scorer id for on chain attestations

- deployments/onchainInfo.json
Reverts OP sepolia updates made [here](https://github.com/passportxyz/passport/pull/2880/files#)
> chore(deployments): update chain

- app/hooks/useOnChainData.tsx
> fix(app): fixing onchain data query key

- platforms/src/GuildXYZ/Providers-config.ts
Fixes: https://github.com/passportxyz/passport/issues/2881
> 2881 audit entire app    capitalize all instances of passport and stamp 3

- app/__test-fixtures__/contextTestHelpers.tsx
- app/__tests__/components/ScrollCampaign.test.tsx
- app/components/ScrollCampaign.tsx
- app/config/scroll_campaign.ts
- app/context/ceramicContext.tsx
- platforms/src/CustomGithub/Providers/condition.ts
- platforms/src/utils/__tests__/githubClient.test.ts
- platforms/src/utils/githubClient.ts
Fixes: https://github.com/passportxyz/passport/issues/2897
> 2897 GitHub account integration 2

- app/hooks/useOneClickVerification.tsx
fixes: https://discord.com/channels/682786569857662976/963185659638607982/1294394412490817536
> fix: call compose retry a single time after onboard completes

- platforms/src/Civic/App-Bindings.tsx
Fixes: https://github.com/passportxyz/passport/issues/2965
> feat: flag Civic as an EVM stamp

- app/context/WalletStoreManager.tsx
> feat(app): check if on campaign page when account changes

- platforms/src/Github/App-Bindings.ts
- platforms/src/Github/Providers-config.ts
> chore(platforms): update copy

- app/__tests__/components/ScrollMintBadge.test.tsx
- app/components/ScrollCampaign.tsx
- app/components/scroll/ScrollConnectGithub.tsx
- app/components/scroll/ScrollInitiateMintBadge.tsx
- app/components/scroll/ScrollMintedBadge.tsx
This fixes https://github.com/passportxyz/passport/issues/2988
> feat(scroll): update text

- platforms/src/Gitcoin/App-Bindings.tsx
> chore(platforms): update link

- iam/.env-example.env
- iam/__tests__/autoVerification.test.ts
- iam/__tests__/index.test.ts
- iam/src/index.ts
- iam/src/utils/autoVerification.ts
- iam/src/utils/credentials.ts
- iam/src/utils/helpers.ts
- iam/src/utils/scorerService.ts
fixes https://github.com/passportxyz/passport/issues/2964
> feat(iam): adding auto-verify endpoint

- app/__tests__/components/Notifications.test.tsx
- app/components/Notifications.tsx
- app/hooks/useNotifications.tsx
Fixes: https://github.com/passportxyz/passport/issues/3000
> feat(app): delete all notifications button

- platforms/src/Linkedin/Providers/linkedin.ts
this fixes https://github.com/passportxyz/passport/issues/2915
> feat(linkedin): update request call

- .github/workflows/build_and_deploy_generic.yml
- .github/workflows/build_and_deploy_production.yml
- .github/workflows/build_and_deploy_review.yml
- .github/workflows/build_and_deploy_staging.yml
- .github/workflows/ci.yml
- .github/workflows/deploy_generic.yml
- .github/workflows/deploy_production.yml
- .github/workflows/deploy_review.yml
- .github/workflows/deploy_staging.yml
- .github/workflows/deploy_ui_production.yml
- .github/workflows/deploy_ui_review.yml
- .github/workflows/deploy_ui_staging.yml
- .github/workflows/release_and_deploy_production.yml
Fixes: https://github.com/passportxyz/core-infra/issues/65
> fix: changing to 1Password ressources that are deleted

- iam/.env-example.env
- platforms/src/AllowList/Providers/allowList.ts
- platforms/src/CustomGithub/Providers/github.ts
- platforms/src/Gitcoin/Providers/__tests__/gitcoinGrantsStatistics.test.ts
- platforms/src/Gitcoin/Providers/gitcoinGrantsStatistics.ts
- platforms/src/GtcStaking/Providers/GtcStaking.ts
- platforms/src/TrustaLabs/Providers/TrustaLabs.ts
Fixes: https://github.com/passportxyz/passport/issues/3048
> fix: drop CGRANTS_API_TOKEN in favour SCORER_API_KEY

- infra/package.json
- infra/yarn.lock
fixes: https://github.com/passportxyz/core-infra/issues/39
> chore(infra): remove awsx package

- iam/__tests__/additional_signer.test.ts
- iam/__tests__/credential_issuance.test.ts
- iam/__tests__/index.test.ts
- iam/src/index.ts
- iam/src/utils/bans.ts
- iam/src/utils/credentials.ts
- iam/src/utils/helpers.ts
- iam/src/utils/revocations.ts
> feat(iam): checking bans before issuing credentials

- platforms/src/Coinbase/Providers/coinbase.ts
- platforms/src/Coinbase/__tests__/coinbase.test.ts
> fix(platforms): explicitly request json response from coinbase API

- app/utils/onChainStamps.ts
This fixes https://github.com/passportxyz/passport/issues/3117
> feat(onChain): update onchain get passport call

- .github/workflows/build_and_deploy_production.yml
- .github/workflows/build_and_deploy_review.yml
- .github/workflows/build_and_deploy_staging.yml
- .github/workflows/ci.yml
- .github/workflows/deploy_production.yml
- .github/workflows/deploy_review.yml
- .github/workflows/deploy_staging.yml
- .github/workflows/deploy_ui_production.yml
- .github/workflows/deploy_ui_review.yml
- .github/workflows/deploy_ui_staging.yml
- .github/workflows/release_and_deploy_production.yml
- infra/aws/iam.ts
Fixes: https://github.com/passportxyz/passport/issues/3108
> fix: load balancer spec in 5XX alarm for iam

- app/components/PlatformCard.tsx
- app/context/scorerContext.tsx
- app/hooks/usePlatforms.ts
- platforms/src/Binance/Providers-config.ts
- platforms/src/Binance/Providers/binance.ts
- platforms/src/Coinbase/Providers-config.ts
- platforms/src/Coinbase/Providers/coinbase.ts
- platforms/src/ETH/Providers/accountAnalysis.ts
- platforms/src/TrustaLabs/Providers-config.ts
- platforms/src/ZkSync/Providers-config.ts
- types/src/index.d.ts
> chore(platforms): deprecating stamps

- platforms/src/Holonym/App-Bindings.tsx
- platforms/src/Holonym/Providers-config.ts
- platforms/src/Holonym/Providers/HolonymPhone.ts
- platforms/src/Holonym/__tests__/holonymPhone.test.ts
- platforms/src/Holonym/index.ts
- types/src/index.d.ts
This fixes https://github.com/passportxyz/passport/issues/3128
> feat(holonymphone): add holonym phone stamp

- platforms/src/Holonym/Providers/HolonymPhone.ts
- platforms/src/Holonym/Providers/holonymGovIdProvider.ts
- platforms/src/Holonym/__tests__/holonymGovId.test.ts
- platforms/src/Holonym/__tests__/holonymPhone.test.ts
This fixes https://github.com/passportxyz/passport/issues/3128
> feat(holonymphone): modify error handling

- app/__test-fixtures__/contextTestHelpers.tsx
- app/__tests__/components/CardList.test.tsx
- app/components/CardList.tsx
- app/components/PlatformCard.tsx
- app/components/PlatformDetails.tsx
- app/context/scorerContext.tsx
- platforms/src/Holonym/App-Bindings.tsx
- platforms/src/Holonym/Providers-config.ts
fixes https://github.com/passportxyz/passport/issues/3134
> fix(app): making distinction between technically possible points and points to tell the user about

- platforms/src/Idena/__tests__/provider.test.ts
- platforms/src/Idena/procedures/idenaSignIn.ts
> fix(platforms): catching and reporting errors from the Idena API

- embed/__tests__/autoVerification.test.ts
- embed/src/autoVerification.ts
> feat(embed): added optional credentialIds param to limit the credentials checked

- app/utils/chains.ts
Fixes: https://github.com/passportxyz/passport/issues/3220
> feat: reordering chains in popup

- .github/workflows/embed.yml
this fixes https://github.com/passportxyz/passport/issues/3193
> feat(embed): add workflow for embed popup

- .github/workflows/embed.yml
- infra/aws/embed.ts
this fixes https://github.com/passportxyz/passport/issues/3193
> Workflow test

- .github/workflows/embed.yml
this fixes https://github.com/passportxyz/passport/issues/3193
> feat(embed): update node version for workflows

- embed-popup/src/App.tsx
Fixes: https://github.com/passportxyz/passport/issues/3193
> fix: build of popup app

- embed/src/stamps.ts
this fixes https://github.com/passportxyz/passport/issues/3193
> feat(embed): update stamps flag

- platforms/src/Holonym/App-Bindings.tsx
- platforms/src/Holonym/Providers-config.ts
> chore(platforms): update holonym links

- .github/workflows/embed_production.yml
- .github/workflows/embed_review.yml
- .github/workflows/embed_staging.yml
- .github/workflows/release_and_deploy_production.yml
- .github/workflows/sync_to_s3_generic.yml
- app/config/platformMap.ts
- embed-popup/src/platformMap.ts
- platforms/src/Discord/App-Bindings.ts
> feat(workflows): add embed reusable workflows

- .github/workflows/sync_to_s3_generic.yml
> Embed workflows

- .github/workflows/embed_review.yml
> feat(embed): disable trigger

- .github/workflows/build_and_deploy_staging.yml
> disable linter for staging

- .github/workflows/deploy_staging.yml
> disable linter deploy_staging.yml

- .github/workflows/embed_production.yml
- .github/workflows/embed_review.yml
- .github/workflows/embed_staging.yml
- .github/workflows/release_and_deploy_production.yml
> feat(embed): inherit secrets

- app/__tests__/pages/Dashboard.test.tsx
- app/__tests__/pages/Welcome.test.tsx
- app/package.json
- app/pages/_app.tsx
- database-client/package.json
- schemas/package.json
- yarn.lock
Fixes: https://github.com/passportxyz/passport/issues/3288
> fix: remove unnecesary packages

- embed-popup/src/App.tsx
This fixes https://github.com/passportxyz/passport/issues/3298
> feat(embed): add debug flag to prevent close popup

- .github/workflows/embed_review.yml
- embed/src/stamps.ts
this fixes https://github.com/passportxyz/passport/issues/3295
> feat(embed): remove coinbase stamp

- infra/aws/embed.ts
- infra/aws/iam.ts
Fixes: https://github.com/passportxyz/passport/issues/3303
> feat: updating infra to load keys for epoch 1 from secrets

- yarn.lock
this fixes 
https://github.com/passportxyz/passport/issues/3298
https://github.com/passportxyz/passport/issues/3296
> feat(embed): update yarn lock

- app/components/WelcomeFooter.tsx
Fixes: https://github.com/passportxyz/passport/issues/3297
> feat: update passport app links

- embed-popup/src/App.tsx
Fixes: https://github.com/passportxyz/passport/issues/3326
> feat: prevent embed popup close when localstorage flag is present

- infra/aws/embed.ts
- infra/aws/iam.ts
this fixes https://github.com/passportxyz/core-infra/issues/70
> feat(infra): ignore desiredCount from pulumi changes

- app/components/EmbedCampaign.tsx
Fixes: https://github.com/passportxyz/passport/issues/3336
> fix: sizing of settings options in embed campaign page

- infra/aws/embed.ts
- infra/aws/iam.ts
> chore(infra): setting static names for ECS roles

- app/utils/onChainStamps.ts
- this affects users that do not have a passport attestation (which is now deprected), as it will not load the provider list
Fixes: https://github.com/passportxyz/passport/issues/3359
> fix: retreive onchain passport regardles of attestation uuid

- .github/workflows/deploy_generic.yml
- .github/workflows/deploy_production.yml
- .github/workflows/deploy_review.yml
- .github/workflows/deploy_staging.yml
Fixes: https://github.com/passportxyz/passport/issues/3344
> fix: install aws cli as per AWS guide

- .github/workflows/ci.yml
- .github/workflows/deploy_ui_production.yml
- .github/workflows/deploy_ui_review.yml
- .github/workflows/deploy_ui_staging.yml
- .github/workflows/release_and_deploy_production.yml
- .github/workflows/sync_to_s3_generic.yml
- .github/workflows/sync_to_s3_generic_app.yml
Fixes: https://github.com/passportxyz/core-infra/issues/106
> feat: have created workflow to push app to S3

- .github/workflows/build_and_deploy_generic.yml
Pass the session_token to the build_and_push action
> feat: pass on session_token to build_and_push action

- app/context/datastoreConnectionContext.tsx
- app/hooks/useLoginFlow.tsx
this fixes https://github.com/passportxyz/passport/issues/3277
> feat(logs): remove debug logs

- .github/workflows/deploy_app_generic.yml
- .github/workflows/release_and_deploy_production.yml
- infra/aws/embed.ts
- infra/aws/iam.ts
- infra/aws/index.ts
- infra/aws/stacks.ts
Fixes: https://github.com/passportxyz/passport/issues/3371
> feat: drop amplify and jobs pushing to branch monitored by amplify

- embed/src/server.ts
> chore(embed): remove ratelimiting exemption for /verify

- .github/workflows/deploy_app_generic.yml
- .github/workflows/deploy_embed_generic.yml
- .github/workflows/sync_to_s3_generic_build_app.yml
Fixes: https://github.com/passportxyz/passport/issues/3395
> feat: optimize the sequence of jobs for deploying the app

- .github/workflows/build_and_deploy_generic.yml
- .github/workflows/build_and_deploy_production.yml
- .github/workflows/build_and_deploy_review.yml
- .github/workflows/build_and_deploy_staging.yml
- .github/workflows/deploy_app_generic.yml
- .github/workflows/deploy_embed_generic.yml
- .github/workflows/deploy_generic.yml
- .github/workflows/deploy_production.yml
- .github/workflows/deploy_review.yml
- .github/workflows/deploy_staging.yml
- .github/workflows/release_and_deploy_production.yml
- .github/workflows/sync_to_s3_generic_build_app.yml
- .github/workflows/sync_to_s3_generic_build_embed.yml
- .github/workflows/sync_to_s3_generic_push_app.yml
- .github/workflows/sync_to_s3_generic_push_embed.yml
Fixes: https://github.com/passportxyz/passport/issues/3395
> feat: upgrade gh_workflow versino to v3

- .github/workflows/infra.yml
this fixes https://github.com/passportxyz/passport/issues/3309
> feat(workflow): add infra only workflow

- identity/src/humanNetworkOprf.ts
> chore(identity): enable error reporting for human network wasm lib

- .github/workflows/build_and_deploy_generic.yml
- .github/workflows/deploy_generic.yml
- .github/workflows/infra.yml
- .github/workflows/sync_to_s3_generic_push_app.yml
- .github/workflows/sync_to_s3_generic_push_embed.yml
- identity/package.json
- yarn.lock
> chore(app): use custom mishtiwasm with error logging

- platforms/src/CleanHands/Providers-config.ts
Fixes: https://github.com/passportxyz/passport/issues/3350
> 3350 create new stamp provider for proof of clean hands 1

- platforms/src/CleanHands/App-Bindings.tsx
- platforms/src/CleanHands/Providers-config.ts
- platforms/src/CleanHands/Providers/__tests__/cleanHands.test.ts
- platforms/src/CleanHands/Providers/index.ts
- platforms/src/utils/signer.ts
Fixes: https://github.com/passportxyz/passport/issues/3350
> 3350 create new stamp provider for proof of clean hands 2

- embed/.env-example.env
- embed/src/jest.setup.ts
- embed/src/server.ts
- iam/.env-example.env
- iam/src/index.ts
- iam/src/jest.setup.ts
- platforms/jest.setup.js
- platforms/src/CleanHands/Providers/__tests__/cleanHands.test.ts
- platforms/src/CleanHands/Providers/index.ts
Fixes: https://github.com/passportxyz/passport/issues/3350#issue-2932350336
> feat: adding api key to requests made to sign protocol

- embed/src/server.ts
> fix(embed-popup): temporary rate limit adjustment

- embed/__tests__/server.test.ts
- embed/src/handlers.ts
- embed/src/server.ts
Fixes: https://github.com/passportxyz/passport/issues/3439
> feat: add api to load only score & stamps

- app/pages/Version.tsx
- app/pages/index.tsx
Fixes: https://github.com/passportxyz/passport/issues/3400
> feat: adding Version page accessible at

- platforms/src/Github/Providers/__tests__/githubContributionActivity.test.ts
- platforms/src/Github/Providers/githubContributionActivity.ts
> chore(platforms): small change to github stamp failure message

- app/package.json
- iam/src/utils/logger.ts
- yarn.lock
fixes https://github.com/passportxyz/passport/issues/3476
> fix(iam): fix missing trailing args in logs

- embed/__tests__/handler.test.ts
- embed/__tests__/metadataHandler.test.ts
- embed/__tests__/rateLimiter.test.ts
- embed/src/main.ts
- embed/src/rateLimiter.ts
- embed/src/server.ts
- embed/src/utils/logger.ts
- iam/src/utils/logger.ts
fixes https://github.com/passportxyz/passport/issues/3476
> fix(iam,embed): fixing logger in embed service, embed rate limits

- platforms/src/Binance/Providers-config.ts
- platforms/src/Binance/Providers/binance.ts
- platforms/src/Coinbase/Providers-config.ts
- platforms/src/Coinbase/Providers/coinbase.ts
> chore(platforms): cleaning up deprecated code

- app/package.json
Fixes: https://github.com/passportxyz/passport/issues/3486
> feat: updated the used embed version

- platforms/src/ETH/Providers/accountAnalysis.ts
Fixes: https://github.com/passportxyz/passport/issues/3494
> fix: need to include base model in account analysis

- platforms/package.json
- yarn.lock
> chore: upgrade human-id-sdk

- identity/__tests__/credentials.test.ts
- identity/package.json
- identity/src/nullifierGenerators.ts
- yarn.lock
> chore: upgrading mishtiwasm, hashing after oprf again

- app/config/platformMap.ts
- app/hooks/usePlatforms.tsx
- platforms/src/Biometrics/App-Bindings.tsx
- platforms/src/Biometrics/Providers-config.ts
- platforms/src/Biometrics/Providers/Biometrics.ts
- platforms/src/Biometrics/Providers/index.ts
- platforms/src/Biometrics/__tests__/biometrics.test.ts
- platforms/src/Biometrics/index.ts
- platforms/src/platforms.ts
- types/src/index.d.ts
> feat: add Biometrics stamp

- CLAUDE.md
- app/components/ActionOrCancelModal.tsx
- app/components/RemovePlatformModal.tsx
- app/components/StampDrawer/components/DrawerHeader.tsx
- app/components/StampDrawer/index.tsx
- app/components/StampDrawer/types.ts
> feat(app): added back stamp drawer menu

- app/components/PlatformCard.tsx
- platforms/src/Biometrics/Providers-config.ts
Fixes: https://github.com/passportxyz/passport/issues/3560
> feat: update biometrics platform logo

- app/pages/Welcome.tsx
Fixes: https://github.com/passportxyz/passport/issues/3560
> feat: link to points program post in inboarding screen

- app/__tests__/components/HumanIDPlatform.test.tsx
- app/__tests__/pages/Dashboard.test.tsx
- app/components/DashboardScorePanel.tsx
- app/components/GenericPlatform.tsx
- app/components/InitiateReverifyStampsButton.tsx
- app/components/RemovePlatformModal.tsx
- app/components/StampDrawer/components/DrawerHeader.tsx
- app/components/StampDrawer/components/PlatformGuide.tsx
- app/components/StampDrawer/components/PointsModule.tsx
- app/pages/Dashboard.tsx
- platforms/src/Biometrics/Providers-config.ts
- platforms/src/CleanHands/Providers-config.ts
- platforms/src/HumanIdKyc/App-Bindings.ts
- platforms/src/HumanIdKyc/Providers-config.ts
- platforms/src/HumanIdPhone/App-Bindings.ts
- platforms/src/HumanIdPhone/Providers-config.ts
This PR includes several language improvements and UI enhancements to the Passport app:
- **Step-by-step guide header**: Added a consistent 'Step-by-step guide' header to all steps sections in the PlatformGuide component, similar to how 'Important Considerations' works for other sections
- Updated various user-facing text throughout the application for better clarity and consistency
- Improved messaging across multiple components including:
- Dashboard score panel
- Platform guides and modals
- Human.tech provider descriptions
- Stamp management interfaces
- Modified `app/components/StampDrawer/components/PlatformGuide.tsx` to show 'Step-by-step guide' header when no custom title is provided
- Updated provider configurations in platforms directory
- Enhanced user experience with more …
> feat: add Step-by-step guide header and update language across Passport app

- infra/aws/hn_signer.ts
fixes https://github.com/passportxyz/passport/issues/3537
> fix: remove hn-signer health check more

- platforms/package.json
- yarn.lock
Fixes bug where users get "invalid issuer" when trying to claim a valid KYC SBT
Fixes: https://github.com/passportxyz/passport/issues/3588
> fix(platforms): upgrade human-id-sdk to 0.0.12

- app/__tests__/components/CardList.test.tsx
- app/__tests__/components/PlatformCard.test.tsx
- app/__tests__/pages/Dashboard.test.tsx
- app/__tests__/pages/Home.test.tsx
- app/components/PlatformCard.tsx
- app/pages/Home.tsx
- app/pages/Welcome.tsx
- app/utils/helpers.tsx
Fixes: https://github.com/passportxyz/passport/issues/3560
> fix: remove console.log

- app/components/NetworkCard.tsx
Fixes: https://github.com/passportxyz/passport/issues/3591
> fix: prefix for network card human points label

- .claude/knowledge/KNOWLEDGE_MAP.md
- .claude/knowledge/KNOWLEDGE_MAP_CLAUDE.md
- .claude/knowledge/architecture/platform_system.md
- .claude/knowledge/conventions/error_handling.md
- .claude/knowledge/gotchas/platform_identification.md
- .claude/knowledge/patterns/humanid_platforms.md
- .claude/knowledge/testing/provider_testing.md
- platforms/package.json
- platforms/src/Biometrics/App-Bindings.tsx
- platforms/src/Biometrics/Providers/Biometrics.ts
- platforms/src/Biometrics/__tests__/biometrics.test.ts
- platforms/src/Biometrics/constants.ts
- platforms/src/CleanHands/App-Bindings.tsx
- platforms/src/CleanHands/Providers-config.ts
- platforms/src/CleanHands/Providers/__tests__/cleanHands.test.ts
- platforms/src/CleanHands/Providers/index.ts
- platforms/src/CleanHands/constants.ts
- platforms/src/CleanHands/index.ts
- platforms/src/HumanID/shared/BaseHumanIDPlatform.ts
- platforms/src/HumanID/shared/BaseHumanIdProvider.ts
- platforms/src/HumanID/shared/__tests__/BaseHumanIDPlatform.test.ts
- platforms/src/HumanID/shared/__tests__/utils.test.ts
- platforms/src/HumanID/shared/utils.ts
- platforms/src/HumanIdKyc/App-Bindings.ts
- platforms/src/HumanIdKyc/Providers/humanIdKyc.ts
- platforms/src/HumanIdKyc/constants.ts
- platforms/src/HumanIdPhone/App-Bindings.ts
- platforms/src/HumanIdPhone/Providers/humanIdPhone.ts
- platforms/src/HumanIdPhone/constants.ts
- yarn.lock
> feat: use embedded clean hands and biometrics

- app/__tests__/components/StampDrawer/CTAButtons.test.tsx
- app/__tests__/components/StampDrawer/PlatformGuide.test.tsx
- app/__tests__/components/StampDrawer/index.test.tsx
- app/components/StampDrawer/components/CTAButtons.tsx
- app/components/StampDrawer/components/PlatformGuide.tsx
- app/components/StampDrawer/components/PointsModule.tsx
- platforms/src/Biometrics/Providers-config.ts
- platforms/src/CleanHands/Providers-config.ts
- platforms/src/HumanID/shared/BaseHumanIDPlatform.ts
- platforms/src/HumanID/shared/types.ts
- platforms/src/HumanID/shared/utils.ts
- platforms/src/HumanIdKyc/Providers-config.ts
- platforms/src/HumanIdPhone/Providers-config.ts
- platforms/src/types.ts
Closes #3710. 
Depends on this PR: https://github.com/passportxyz/passport/pull/3716
Replaces this PR: https://github.com/passportxyz/passport/pull/3710
> Remove silksecure.net links. Use Human ID modal instead.
