- app/__tests__/components/ProviderCards/BrightidCard.test.tsx
- app/__tests__/components/ProviderCards/EnsCard.test.tsx
- app/__tests__/components/ProviderCards/FacebookCard.test.tsx
- app/__tests__/components/ProviderCards/GoogleCard.test.tsx
- app/__tests__/components/ProviderCards/PoapCard.test.tsx
- app/__tests__/components/ProviderCards/PohCard.test.tsx
- app/__tests__/components/ProviderCards/TwitterCard.test.tsx
- app/__tests__/components/VerifyModal.test.tsx
- app/components/ProviderCards/BrightidCard.tsx
- app/components/ProviderCards/EnsCard.tsx
- app/components/ProviderCards/FacebookCard.tsx
- app/components/ProviderCards/GoogleCard.tsx
- app/components/ProviderCards/PoapCard.tsx
- app/components/ProviderCards/PohCard.tsx
- app/components/ProviderCards/TwitterCard.tsx
- app/components/VerifyModal.tsx
- app/context/userContext.tsx
- loading spinners should be extended until stamp actually displays 'verified'
- changes passport operations (handleCreatePassport, handleAddStamp) to be async
- adds VerifyModal.test.tsx
[#103]
> feat(app): extend loading spinners until stamp verification is complete

- iam/src/utils/providers.ts
message: "I commit that this stamp is my unique and only <provider name> verification for Passport."
[resolves #166]
Examples:
> feat(iam): customize wallet signing message when verifying stamps

- app/__tests__/components/Card.test.tsx
- app/__tests__/components/ProviderCards/BrightidCard.test.tsx
- app/__tests__/components/ProviderCards/EnsCard.test.tsx
- app/__tests__/components/ProviderCards/FacebookCard.test.tsx
- app/__tests__/components/ProviderCards/GoogleCard.test.tsx
- app/__tests__/components/ProviderCards/PoapCard.test.tsx
- app/__tests__/components/ProviderCards/PohCard.test.tsx
- app/__tests__/components/ProviderCards/TwitterCard.test.tsx
- app/__tests__/pages/Dashboard.test.tsx
- app/__tests__/pages/Home.test.tsx
- app/__tests__/pages/index.test.tsx
- app/components/Card.tsx
- app/context/userContext.tsx
- app/pages/Dashboard.tsx
- database-client/integration-tests/ceramicDatabaseTest.ts
- database-client/src/ceramicClient.ts
- database-client/src/types.ts
This PR ensures that `createPassport` is only called if we get a response from ceramic and that response is empty.
--
related to #196
> fix: only creates a new passport if we get an empty response from ceramic

- app/__tests__/components/JsonOutputModal.test.tsx
- app/components/JsonOutputModal.tsx
This PR adds a download button on the modal that shows the passport in JSON format.
[#195](https://github.com/gitcoinco/dPopp/issues/195)
> feat(passport): enable the download of passport as JSON file

- database-client/src/ceramicClient.ts
fix(database-client): pin passport streams when fetched and when adding a stamp
we discovered an issue where passport streams were not being pinned when they were created. ceramic
team is already working on a fix for that issue, that will address newly-created passports going
forward. this fix will address existing passports that were already created without being pinned
previously
[#241]
> fix(database-client): pin passport streams when fetched and when adding a stamp

- app/pages/_app.tsx
use NEXT_PUBLIC_CERAMIC_CLIENT_URL as self.id Provider configuration, defaults to "testnet-clay"
(community node)
[fixes #220]
> fix(app): use ceramic client url for self.id Provider

- iam/__tests__/index.test.ts
- iam/src/index.ts
- iam/tsconfig.json
refactor(iam): use different http status codes for different iam error response types
previously all error responses returned 400 Bad Request codes. this change returns different codes
(401, 403, 500) for certain situations. also adds `__tests__` to iam tsconfig to resolve
esModuleInterop warning on `supertest` library usage
[#70]
> refactor(iam): use different http status codes for different iam error response types

- database-client/integration-tests/ceramicDatabaseTest.ts
test(database-client): generate a new random DID for ceramic integration tests
Ceramic integration tests are now consistently timing out (and failing). It seems to be due to the
enormous number of commits logged when using the same DID for all test runs that causes tests to
time out. Replacing this with a newly generated DID each time results in fast-enough integration
tests that pass more consistently.
> test(database-client): generate a new random DID for ceramic integration tests

- database-client/integration-tests/ceramicDatabaseTest.ts
test(database-client): assert equality on method results, instead of method reference
also fix `getPassport retrieves the passport and stamps from ceramic` test to assert against
existingPassport date instead of today's date
> test(database-client): assert equality on method results, instead of method reference

- app/__test-fixtures__/contextTestHelpers.tsx
- app/__tests__/components/Card.test.tsx
- app/__tests__/pages/Dashboard.test.tsx
- app/components/Card.tsx
- app/context/ceramicContext.tsx
- app/pages/Dashboard.tsx
chore(app): use enum for isLoadingPassport type instead of "boolean | undefined"
this should improve readability and prevent possible future bugs from boolean logic and the
falsiness of 'undefined'
[resolves #275]
> chore(app): use enum for isLoadingPassport type instead of "boolean | undefined"

- iam/__tests__/discord.test.ts
- iam/__tests__/index.test.ts
- iam/src/index.ts
- iam/src/providers/discord.ts
- iam/src/utils/providers.ts
- identity/src/credentials.ts
- types/src/index.d.ts
This PR refactors to allow for multiple VCs to be requested and issued from the IAM server.
--
refers: #377
> feat: allows for user to request multiple VCs in single req

- platforms/src/Ens/App-Bindings.ts
Support flagged that Passport holders are unaware they need to set up reverse records to verify ENS. Here's a PR to add a banner to the ENS stamp to address that.
> add-ENS-stamp-banner

- app/__test-fixtures__/contextTestHelpers.tsx
- app/__tests__/components/GenericPlatform.test.tsx
- app/__tests__/components/ProviderCards/BrightidCard.test.tsx
- app/__tests__/components/ProviderCards/EnsCard.test.tsx
- app/__tests__/components/ProviderCards/GitPOAPCard.test.tsx
- app/__tests__/components/ProviderCards/PoapCard.test.tsx
- app/__tests__/components/ProviderCards/PohCard.test.tsx
- app/__tests__/pages/Dashboard.test.tsx
- app/__tests__/pages/Home.test.tsx
- app/context/userContext.tsx
- app/pages/Dashboard.tsx
- app/pages/Home.tsx
This PR adds a feature to disconnect the user's wallet and navigate to the landing page when the passport logo is clicked in the dashboard.
closes #841
> feat: link passport logo to landing

- app/context/userContext.tsx
The default CACAO expiry time is 1 week. Currently the passport app has the expiry time set to 1 day. If there is any trouble with the Ceramic anchor service used by the passport Ceramic node, 1 day is a pretty short period to recover from issues. Setting it to the default 1 week gives more room for recovering from potential errors.
> Use default CACAO expiry time

- app/components/RemoveStampModal.tsx
- app/context/ceramicContext.tsx
This PR introduces the following
* close remove stamp modal on failure
* log stamp related errors in `ceramicContext.ts` to datadog
close #879
> feat: close remove stamp modal on failure

- app/package.json
This adds the commit hash env variable for exports as well.
Closes: https://github.com/gitcoinco/passport/issues/860
> feat(app,git commit): adding env variable for git commit for export

- app/components/RefreshMyStampsModalContentCard.tsx
fixes: [1135](https://github.com/gitcoinco/passport/issues/1135)
This PR removes the outline shown below:
> fix(app): remove outline on accordian

- app/__tests__/context/ceramicContext.test.tsx
- app/context/ceramicContext.tsx
- database-client/__tests__/passportScorerClient.test.ts
- database-client/src/passportScorerClient.ts
fixes: #1599 it also removes a duplicate fetch request that is called on initial load of the app
> 1599 optimize requests

- app/context/onChainContext.tsx
- app/context/userContext.tsx
fixes: https://github.com/gitcoinco/passport/issues/1818
- make sure to reconnect to ceramic only if address changed
- when reloading on-chain state, react only on wallet changes as it might be out of sync with `address`
> fix(app): fix some synchronisation issues

- app/utils/onboard.ts
Fixes: https://github.com/gitcoinco/passport/issues/1983
Safety update from walletconnect: https://twitter.com/WalletConnect/status/1735346187958432103
Update 📢
A fix has been deployed, and the genuine and verified Ledger Connect Kit version 1.1.8 is now propagating. 
We have worked closely with 
[@Ledger](https://twitter.com/Ledger)
to disable a project ID thought to have been used to target users with phishing attacks, and have reported the suspected address.
Dapps using WalletConnect's services and products will not have been directly affected, but we continue to remind any that also use Ledger's Connect Kit or wagmi LedgerConnector to update their version of these immediately.
In our mission of connecting Web3, safety is critical, which is why we continue to focus on establishing …
> chore(app): re enable wallet connect

- iam/__tests__/easFees.test.ts
- iam/src/utils/easFees.ts
- infra/aws/index.ts
This fixes: https://github.com/gitcoinco/passport/issues/2252
It also adds actions to `okActions`, as indicated in this PD guide: https://support.pagerduty.com/docs/amazon-cloudwatch-integration-guide
> 2252 catch moralis errors

- infra/aws/iam_secrets.ts
Fixes: https://github.com/gitcoinco/passport/issues/2506
> fix: get the OUTDID_API_SECRET from the correct secrets manager

- app/__tests__/hooks/useOneClickVerification.test.tsx
- app/hooks/useOneClickVerification.tsx
Fixes: When completing the one click onboard flow platform ids are currently being passed to the verify function, but it is expecting provider ids
> fix(app): pass individual provider ids instead of platform ids

- iam/src/index.ts
- infra/aws/index.ts
- platforms/src/utils/__tests__/providers.test.ts
- platforms/src/utils/providers.ts
> 2515 handle long running requests

- app/__tests__/components/CardList.test.tsx
- app/components/CardList.tsx
- app/components/Category.tsx
- app/components/DropDownIcon.tsx
- app/components/PlatformCard.tsx
- types/src/index.d.ts
This fixes: https://github.com/gitcoinco/passport/issues/2437
> 2437 collapsible stamps 2

- app/__tests__/pages/Dashboard.test.tsx
- app/pages/Dashboard.tsx
> feat(app): removing JSON button and popup

- app/__tests__/components/GenericPlatform.test.tsx
- app/__tests__/context/stampClaimingContext.test.tsx
- app/components/GenericPlatform.tsx
- app/components/InitiateReverifyStampsButton.tsx
- app/components/Notifications.tsx
- app/context/stampClaimingContext.tsx
> fix: need to click next twice and verification error

- platforms/src/Civic/Providers/types.ts
- platforms/src/Civic/__tests__/civic.test.ts
Civic is changing its process for the creation of new pass types - specifically we are no longer using incremental [slotIds](https://whitepaper.sftlabs.io/SFT%20Whitepaper.pdf), but instead using 32-byte keys, to improve interoperability between  different chains.
This PR makes the minor changes to the passport integration to support this. The change is forwards-compatible, has no effect on user-experience, and can be merged at any time without first consulting Civic.
> chore(platforms): changing slotId in civic pass api response from a number to a hex string

- infra/aws/index.ts
- platforms/src/Linkedin/App-Bindings.ts
This fixes https://github.com/passportxyz/passport/issues/2767
> 2767 passportxyz migration

- iam/src/utils/scorerService.ts
fixes https://github.com/passportxyz/passport/issues/2911
> fix(iam): updating score URL

- app/components/CustomDashboardPanel.tsx
> fix: shape logo covered body of scorer info widget popup

- platforms/src/Discord/Providers-config.ts
- platforms/src/ETH/App-Bindings.ts
- platforms/src/Ens/App-Bindings.ts
- platforms/src/Gitcoin/App-Bindings.tsx
- platforms/src/Github/App-Bindings.ts
- platforms/src/Holonym/App-Bindings.tsx
- platforms/src/Lens/App-Bindings.ts
- platforms/src/TrustaLabs/App-Bindings.tsx
Fixes: https://github.com/passportxyz/passport/issues/2881
> fix: another set of spelling corrections

- app/__test-fixtures__/contextTestHelpers.tsx
- app/__tests__/context/ceramicContext.test.tsx
- app/context/ceramicContext.tsx
- app/hooks/useOneClickVerification.tsx
fixes: {\"error\":\"Commit to stream  rejected because it builds on stale state. Calling 'sync()' on the stream handle will synchronize the stream state in the client with that on the Ceramic node.  Rejected commit CID:...
> fix: call compose retry once onboarding is complete

- platforms/src/GtcStaking/Providers-config.ts
- platforms/src/Idena/App-Bindings.ts
- platforms/src/Idena/Providers-config.ts
> chore(platforms): updating Staking and Idena descriptions

- infra/aws/index.ts
- infra/package.json
- infra/yarn.lock
This fixes https://github.com/passportxyz/core-infra/issues/67
> update amplify branch for review

- infra/aws/index.ts
Fixes: https://github.com/passportxyz/passport/issues/3023
> feat: adding alarm that monitors %xx errors in IAM

- app/__tests__/components/CardList.test.tsx
- app/__tests__/components/StampSelector.test.tsx
- app/components/CardList.tsx
- app/components/StampSelector.tsx
- platforms/src/Outdid/Providers-config.ts
- platforms/src/index.ts
- platforms/src/platforms.ts
- platforms/src/types.ts
- platforms/src/utils/__tests__/createProviders.test.ts
- platforms/src/utils/__tests__/providers.test.ts
- platforms/src/utils/createProviders.ts
- platforms/src/utils/providers.ts
> feat(platforms): adding isDeprecated option to providers, reject verification

- platforms/src/ETH/Providers/accountAnalysis.ts
- platforms/src/ETH/__tests__/accountAnalysis.test.ts
- platforms/src/ZkSync/__tests__/accountAnalysis.test.ts
> feat(platforms): updating eth stamp to use aggregate model

- platforms/src/Coinbase/App-Bindings.tsx
- platforms/src/Coinbase/Providers/coinbase.ts
- platforms/src/Coinbase/__tests__/coinbase.test.ts
- yarn.lock
> chore(platforms): using new coinbase oauth endpoints

- embed/__tests__/rateLimiter.test.ts
- embed/src/rateLimiter.ts
Fixes: https://github.com/passportxyz/passport/issues/3294
> 3294 bug embed cant handle unlimited api keys

- embed/__tests__/metadataHandler.test.ts
- embed/jest.config.ts
- embed/package.json
- embed/src/index.ts
- embed/src/main.ts
- embed/src/redis.ts
- embed/src/server.ts
- embed/src/utils/logger.ts
- iam/__tests__/easFees.test.ts
- iam/__tests__/index_verify.test.ts
- iam/package.json
- iam/src/index.ts
- iam/src/main.ts
- iam/src/utils/easFees.ts
- iam/src/utils/logger.ts
- iam/src/utils/revocations.ts
- identity/__tests__/credentials.test.ts
- identity/jest.config.ts
- identity/src/credentials.ts
- identity/src/humanNetworkOprf.ts
- identity/src/index.ts
- identity/src/keyManager.ts
- identity/src/logger.ts
- identity/src/nullifierGenerators.ts
- identity/src/serverUtils/errorHandlerMiddleware.ts
- identity/src/verification.ts
- identity/src/verifyDidChallenge.ts
- package.json
- yarn.lock
this fixes https://github.com/passportxyz/passport/issues/3419
> feat(logging): add iam logger

- platforms/src/GuildXYZ/Providers-config.ts
This PR updates the GuildXYZ provider configuration to clarify the member qualification criteria and improve the user experience.
- **Updated provider description**: Changed from generic 'community activity' to specifically mention 'verified Guild membership and roles' 
- **Clarified qualification requirements**: Added explicit statement that users need 'at least 1 role in the Human Passport Guild for member credentials'
- **Improved consistency**: Enhanced language consistency around Guild membership requirements
The previous description was somewhat vague about what constitutes qualifying 'community activity'. This update makes it crystal clear that users need verified Guild membership with at least one role in the Human Passport Guild to qualify for member credentials.
- ✅ All tests …
> docs: update GuildXYZ provider guide with clearer member qualification criteria

- app/__tests__/components/NetworkCard.test.tsx
- app/components/NetworkCard.tsx
When attestations expire, the network card was still displaying the expiration date UI (clock icon + 'Valid for X days'), which would show negative numbers like 'Valid for -5 days'. This creates a confusing user experience and violates the UX principle of never displaying negative day counts.
fixes #3596
- Modified NetworkCard.tsx: Added conditional hidden class to the expiration date UI div when expired is true
- Preserved existing functionality: The 'Expired' label continues to show appropriately for expired attestations  
- Leveraged existing state: Used the existing expired boolean variable that checks status === OnChainStatus.MOVED_EXPIRED
Before: Expiration UI always displayed, showing negative day counts for expired attestations
After: Expiration UI hidden when attestation is …
> Hide expiration date UI for expired attestations

- app/components/PlatformCard.tsx
- Change possibleHumanPoints fallback from 0 to undefined for platforms without HUMN points
- Update visibility condition to explicitly check for positive values
- Ensures only stamps with actual HUMN points show the UI element
Fixes #3648
> fix(app): Remove extra 0 on unverified stamp cards without HUMN points
